### ISSUE TITLE
Is this line of code in `PresentationDocument.cs ` copied from SpreadsheetDocument.cs?

### ISSUE THREAD

**Issue by yiding-he** [dotnet/Open-XML-SDK#1061]
https://github.com/OfficeDev/Open-XML-SDK/blob/1623785d49ce279c1c9319c509a2a6a9d3fe05a8/src/DocumentFormat.OpenXml/Packaging/PresentationDocument.cs#L227

![firefox_mkMf3uH120](https://user-images.githubusercontent.com/900606/140247806-979b2f47-dfc5-4106-aaec-a8f4e456618c.png)

Because it obviously doesn't make sence.

**Comment by twsouthwick** [comment]
ha yeah, that's weird. Probably should change that to the appropriate extensions for presentation. Happy to take a PR for that

**Comment by tomjebo** [comment]
Looks like this was fixed already. Reopen if you find that it's not. Closing.
