### ISSUE TITLE
No support of System.IO.Packaging.Package.Save()/Flush() in .NET Core

### ISSUE THREAD

**Issue by mhoerandner** [dotnet/Open-XML-SDK#1211]
Since _OpenXml_ is based on _System.IO.Packaging_ and there is no support for `Flush()`/`Save()` in .NET Core (dotnet 5, ...), I wanted to ask whether OpenXml is planning a better alternative than closing (disposing) the whole `OpenXmlPackage` (e.g. WordprocessingDocument)?

```cs
/// <summary>
/// Gets a value indicating whether saving the package is supported by calling <see cref="Save"/>. Some platforms (such as .NET Core), have limited support for saving.
/// If <c>false</c>, in order to save, the document and/or package needs to be fully closed and disposed and then reopened.
/// </summary>
#if FEATURE_PACKAGE_FLUSH
public static bool CanSave { get; } = true;
#else
public static bool CanSave { get; }
#endif
```

**Comment by adamshakhabov** [comment]
or we should wait for the implementation of Flush in .NET 8😐: https://github.com/dotnet/runtime/issues/24149

**Comment by mikeebowen** [comment]
Hi @mhoerandner , there are no plans to implement this independently. It is scheduled to be in .Net 8.

**Comment by twsouthwick** [comment]
I've got this working for v3 of the SDK: https://github.com/OfficeDev/Open-XML-SDK/pull/1307

I've replaced the underlying abstraction with our own that we can have much more control over. In the end, we still rely on the System.IO.Packaging.Package APIs, but can now "Reload" the underlying package which will allow this to be enabled.

Once this is merged in, please give it a try and see if it works better for you.

**Comment by twsouthwick** [comment]
I'm not sure when the underlying issue will be fixed... so fixing it on our side instead. Once it works there, we can remove this work around, but this will allow us to move forward with the expected behavior.
