### ISSUE TITLE
Update System.IO.Packaging dependency

### ISSUE THREAD

**Issue by lklein53** [dotnet/Open-XML-SDK#1231]
Hi together,

Would it be possible to update the System.IO.Packaging dependency to include the bug fix of https://github.com/dotnet/runtime/issues/43012 ?

**Comment by hunyu** [comment]
Hi @lklein53 

Which version of Open XML SDK are you using? Which recent version of Open XML SDK, like 2.18, make sure you set your project Target  Framework to [.Net 6.0], and you should be able to install latest version of System.IO.Packaging (including the RC for 7.0). 

Let me know if this answers your question?

Hung-Chun Yu
Open Specifications Support

**Comment by lklein53** [comment]
Hi,
thans for your reply. Yes I am using 2.18 and  installing the corresponding System.IO.Packaging version works. I was just wondering if the default dependency should be changed to  include the bug fix.

**Comment by twsouthwick** [comment]
It should work to manually install the update, but because it's a major version bump, we're waiting until we do a v3. I had hoped to do that for the upcoming release, but I've been busy with other projects. We have a 2.19 release coming up soon, and then hopefully the next one will be v3.0

**Comment by twsouthwick** [comment]
We can take this update if someone wants to prepare a PR for it
