### ISSUE TITLE
Discussion for v3.0.0

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/Open-XML-SDK#1270]
We are going to address a number of technical issues that will require a major change. This version will not be binary compatible with the previous `2.x` versions, but should be source compatible to a degree. We will strive to maintain a migration guide and be aware of what effects changes will have.

This issue is to raise concerns about changes that may be made for discussion. Issues and PRs for this will be flagged using the [Milestone](https://github.com/OfficeDev/Open-XML-SDK/milestone/1)

CI builds for this will be pushed to a feed at: https://openxmlsdk.blob.core.windows.net/feed/index.json

**Comment by Asbjoedt** [comment]
So hi there!
Thx for this issue.

I have this https://github.com/dotnet/Open-XML-SDK/issues/1142, which is high on the agenda in my workplace, and I expect it to be similarly high on the agenda for other heritage institutions.

By the end of this year, we will conclude our project on spreadsheets preservation, and this one issue in particular, is important for us to get resolved.

**Comment by twsouthwick** [comment]
@Asbjoedt One of the things I'm doing is cleaning up the initialization logic so the package is more customizable. I'm hoping to finish that up by the end of February. Once that's done, this kind of thing may be more possible. I'm breaking things up into replaceable parts called [features](https://github.com/dotnet/Open-XML-SDK/blob/main/docs/Features.md).

To be honest, I'm not seeing anything in the issue that would *need* to be in v3.0, but the changes I'm doing for v3.0 should enable building it. Sounds like the validator system would need to be customizeable - that's something I was going to investigate after the packages and parts get cleaned up. Let's continue the conversation in #1142
