### ISSUE TITLE
Bug with Open XML SDK adding 3D model

### ISSUE THREAD

**Issue by liy0na** [dotnet/Open-XML-SDK#1280]
**Describe the bug**
You can no longer add 3D model to PowerPoint in verion 2.19.0

**To Reproduce**
up to version 2.18.0 you can use the following code to add 3D model to your PowerPoint

private static readonly string MODEL_3D_URI = "http://schemas.microsoft.com/office/drawing/2017/model3d";
 OpenXmlUnknownElement unknowElement = new OpenXmlUnknownElement( prefix: "am3d", localName: "model3d", namespaceUri: MODEL_3D_URI );
            OpenXmlAttribute attribute = new OpenXmlAttribute( prefix: "r", localName: "embed", namespaceUri: RELS_URI, value: modelId );
            unknowElement.SetAttribute( attribute );

Now the 3D part generated with this code is empty.

**Observed behavior**
3D model container is empty

**Expected behavior**
3D model container should have the 3D part in it

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Office version 18.2210.1203.0
 - .NET Target:  .NET Framework
 - DocumentFormat.OpenXml Version: 2.19.0

**Comment by twsouthwick** [comment]
Can you provide a minimal repro? Ideally, a standalone unit test style snippet; a link to a GitHub repo would also work

**Comment by liy0na** [comment]
Sorry due to confidentiality I cannot share the code. However, I made two PowerPoint files with the same code one shows the 3D part (using 2.18.0) and the other doesn't (using 2.19.0). I hope it helps.
The code takes the empty PowerPoint and produce the out versions.

[empty.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/10368122/empty.pptx)
[out_2.18.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/10368123/out_2.18.pptx)
[out_2.19.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/10368124/out_2.19.pptx)

**Comment by tomjebo** [comment]
Closing due to lack of repro code.
