### ISSUE TITLE
Consider a mechanism to control how parts are loaded

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/Open-XML-SDK#1294]
There are a number of things that occur when a package/part is loaded. As time has gone on, we have added some special casing for things, and it is clear that some control would be helpful here for a developer to have access to.

Proposal:

- Add a feature that would allow for customizing loading of parts
- Currently, the loading occurs before we have a chance to modify features, so we would have to have a way to intercept that as well.
- Remove options from OpenSettings to use this mechanism and deprecate those options

**Comment by twsouthwick** [comment]
This has been completed

**Comment by omisler** [comment]
Is this related to "Removed OpenXmlSettings.RelationshipErrorHandlerFactory and associated types and replaced with a built-in mechanism to enable this" 
How is this new mechanism implemented to replace the factory?

**Comment by twsouthwick** [comment]
That is part of it. The main change here was to fix this poing:

> Currently, the loading occurs before we have a chance to modify features, so we would have to have a way to intercept that as well.

Now, parts are not loaded upon creation of the package, so we have a chance to control things after creation.
