### ISSUE TITLE
Consider removing OpenXmlPackage.Close()

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/Open-XML-SDK#1298]
There are two APIs that do the same thing: `Close()` and `Dispose()`. There is no need to have `Close()` as it is better to use the dispose pattern. Let's take v3.0 as a chance to remove this API and just use `Dispose()`.

- [ ] Remove `Close()` usage on `main`
- [x] Obsolete `Close()` on `release/2.20.0`

**Comment by Asbjoedt** [comment]
Good idea! I have been confused about which to use but have just implemented Dispose() so far.

**Comment by ThomasBarnekow** [comment]
I agree. Simpler and streamlined.

**Comment by tomjebo** [comment]
PR #1373 removes Close() for main

**Comment by twsouthwick** [comment]
@tomjebo can this be closed?
