### ISSUE TITLE
New ImagePart is created as .bin instead of real extension

### ISSUE THREAD

**Issue by Asbjoedt** [dotnet/Open-XML-SDK#1305]
**Describe the bug**
I have asked the question on Stackoverflow:
https://stackoverflow.com/questions/75100804/embedding-image-as-new-imagepart-creates-a-bin-file-using-open-xml-sdk

I don't expect to get any answer there, and I am also increasingly curious whether, this is an implementation error but an issue in the SDK.

Issue is, I create new embedded image in Excel and it is saved to ```/xl/media/image.[WhatEverExtensionItIs]```
If I create a new ImagePart with the SDK and feed it data like this:

```
ImagePart new_ImagePart = worksheetPart.AddImagePart(ImagePartType.Tiff);
stream.Position = 0;
new_ImagePart.FeedData(stream);
```

Then the file will be saved as ```/xl/media/image.bin```.

This behaviour it should not do. It should write the extension as .tiff, since this is the ```ImagePartType```, that I specify. Or secondly it should read the stream and identify it as .tiff through i.e. a magic number.

If you unzip the package and change the image extension to real extension, then the image will open perfectly and I have used a TIFF validator to confirm the image is well-formed. 

What do you think of this? Am I doing anything wrong in my implementation, or can we change the SDK to write real extension like Excel does?

**Screenshots**

**To Reproduce**
1. Use the supplied code to stream any TIFF image (or change ImagePartType to any other image type) to a new ImagePart
2. Unzip the spreadsheet and go to /xl/media/ to find the file as a .bin
3. Change extension to .tiff and the image will open perfectly

**Observed behavior**
ImagePart creates a new image with .bin extension

**Expected behavior**
ImagePart should create a new image with extension based on ImagePartType.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Office version: 2212
 - .NET Target: .Net latest version
 - DocumentFormat.OpenXml Version: 2.19

**Comment by faerbersteve** [comment]
I'm having the same issue within the Word document when embedding png files.
In compare with the older version 2.0.5022 of DocumentFormat.OpenXml the image is added there as .png.

@Asbjoedt Do you have a working fix for the issue?

**Comment by Asbjoedt** [comment]
@faerbersteve I think the deleting the above lines are only a part of the way.

I found the following methods in the SDK, which has 0 references. This should be amended, because they are the ones providing the extension and contentType from ImagePartType. I don't have a clear overview of how to proceed from here though.

```
       internal static string GetContentType(ImagePartType imageType)
            => imageType switch
            {
                ImagePartType.Bmp => "image/bmp",
                ImagePartType.Gif => "image/gif",
                ImagePartType.Png => "image/png",
                ImagePartType.Tiff => "image/tiff",

                // ImagePartType.Xbm => "image/xbm",
                ImagePartType.Icon => "image/x-icon",
                ImagePartType.Pcx => "image/x-pcx",

                // ImagePartType.Pcz => "image/x-pcz",
                // ImagePartType.Pict => "image/pict",
                ImagePartType.Jpeg => "image/jpeg",
                ImagePartType.Emf => "image/x-emf",
                ImagePartType.Wmf => "image/x-wmf",
                ImagePartType.Svg => "image/svg+xml",
                _ => throw new ArgumentOutOfRangeException(nameof(imageType)),
            };

        internal static string GetTargetExtension(ImagePartType imageType)
            => imageType switch
            {
                ImagePartType.Bmp => ".bmp",
                ImagePartType.Gif => ".gif",
                ImagePartType.Png => ".png",
                ImagePartType.Tiff => ".tiff",

                // ImagePartType.Xbm => ".xbm",
                ImagePartType.Icon => ".ico",
                ImagePartType.Pcx => ".pcx",

                // ImagePartType.Pcz => ".pcz",
                // ImagePartType.Pict => ".pict",
                ImagePartType.Jpeg => ".jpg",
                ImagePartType.Emf => ".emf",
                ImagePartType.Wmf => ".wmf",
                ImagePartType.Svg => ".svg",
                _ => ".image",
            };
```

**Comment by Asbjoedt** [comment]
Hi @twsouthwick, @tomjebo 

I have written a fix for this, you can see here: https://github.com/dotnet/Open-XML-SDK/compare/main...Asbjoedt:Open-XML-SDK:ImagePartFix?expand=1

I am not entirely sure the fix works, because I have problems building Open XML SDK to test the new code (approx. 200 namespace references are missing). Maybe you can help me out somehow.

The fix does two things:
* Remove any ```.bin``` references for ImagePart
*  Clean up ImagePart code by removing several lines of outcommented code related to image file formats, that were not implemented when the initial code were made.
* The code also recommits the code in the recently approved PR for https://github.com/dotnet/Open-XML-SDK/pull/1304 (this is a mistake from me, I will be better at keeping commits properly branched in the future, but the recommit should not be an issue)

**Comment by twsouthwick** [comment]
This file is where the `.bin` is coming from:

https://github.com/dotnet/Open-XML-SDK/blob/d46f92b2963f1c21415be08fb21532306e55db75/data/parts/ImagePart.json#L6

**Comment by Asbjoedt** [comment]
Great! thx.
I will verify this when 2.20 is released.

**Comment by Asbjoedt** [comment]
Confirmed fix.

**Comment by Wenfengcheng** [comment]
@mikeebowen Not fixed for _ImagePart_ generated by this way:

```
public static string AppendImagePart(this TypedOpenXmlPart typedOpenXmlPart, byte[] stream, string contentType)
{
    var rId = typedOpenXmlPart.GetNextRelationshipId();

    var imagePart = typedOpenXmlPart.AddNewPart<ImagePart>(contentType, rId);

    using var mStream = new MemoryStream();

    mStream.Write(stream, 0, stream.Length);

    mStream.Position = 0;

    imagePart.FeedData(mStream);

    return rId;
}
```

**Comment by mikeebowen** [comment]
@Wenfengcheng , What is the issue you're seeing? Does it use the wrong extension? Does it throw an error? Something else?

**Comment by Wenfengcheng** [comment]
@mikeebowen yeah, the extension is wrong which is .bin file, not the origin image extension.

**Comment by psyvision** [comment]
+1 can confirm the same issue of a `.bin` in `/media/image.bin` using v2.20:

```csharp
var codes = ImageCodecInfo.GetImageDecoders();
var mimeType = codes.First(c => c.FormatID == image.RawFormat.Guid).MimeType;

var imagePart = mainPart.AddImagePart(mimeType); // image/jpeg

using var stream = new MemoryStream();
image.Save(stream, image.RawFormat);
stream.Position = 0;
imagePart.FeedData(stream);
```

**Comment by twsouthwick** [comment]
@mikeebowen can you take a look to see what's different here?

**Comment by twsouthwick** [comment]
We'll track this in the new issue as it looks subtly different
