### ISSUE TITLE
Enable signing for builds

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/Open-XML-SDK#1331]
After the move to the dotnet org, signing has borken for the repo. We need to fix this so we can get builds out to try out v3.0 features.

/cc @tomjebo @mikeebowen not sure who this should be assigned to, but I believe I heard you talking about it at one of the syncs

**Comment by tomjebo** [comment]
Working on it.

**Comment by tomjebo** [comment]
Appears to be working now.

**Comment by twsouthwick** [comment]
Thanks @tomjebo !
