### ISSUE TITLE
CustomXmlPart incorrectly created as "customXML" rather than "customXml"

### ISSUE THREAD

**Issue by SimonSchwendele** [dotnet/Open-XML-SDK#1350]
**Describe the bug**
When I create a new CustomXmlPart in an existing document it is created in "./customXML/item[id].xml" whereas 
word created the directory as "./customXml" rendering the document incomplete.

```csharp

var xmlPart =  """
<?xml version="1.0" encoding="UTF-8"?>
  <test:testCustom xmlns:test="http://testag.ch/testCustom">
    <test:CMX_LoremIpsum>
      <test:Para1>Lorem Ipsum</test:Para1>
      <test:Para2>Dolor sit amet</test:Para2>
      <test:Para3>Consectetur adipiscing elit</test:Para3>
      <test:Para4>den Rest müsste ich googlen</test:Para4>
    </test:CMX_LoremIpsum>
    <test:CMX_DummyTexts>
      <test:Text1>Some text for Field 'Text1'</test:Text1>
      <test:Text2>(ノಠ益ಠ)ノ彡┻━┻</test:Text2>
    </test:CMX_DummyTexts>
  </test:testCustom>
""";

var part = Document.GetOrCreateCmiCustomXmlPart();
using var partStream = part.GetStream(FileMode.Create,
                                              FileAccess.ReadWrite);

if (partStream.CanSeek)
            partStream.Seek(0, SeekOrigin.Begin);

var doc = XDocument.Parse(xmlPart);

using var xmlWriter = XmlWriter.Create(partStream);
doc.Save(xmlWriter);



    public static CustomXmlPart GetOrCreateCustomXmlPart(this WordprocessingDocument wordDoc,
                                                         string partId)
    {
        wordDoc.MainDocumentPart!.TryGetPartById(partId,
                                                 out var found);
        var part = found as CustomXmlPart;

        part ??= wordDoc.MainDocumentPart!.AddCustomXmlPart(CustomXmlPartType.CustomXml,
                                                            partId);

        var customXmlProps = part.CustomXmlPropertiesPart ?? part.AddNewPart<CustomXmlPropertiesPart>();
        customXmlProps.DataStoreItem ??= new DataStoreItem() { ItemId = Guid.NewGuid().ToString("B") };

        return part;
    }
```

**Observed behavior**
`AddCustomXmlPart` appears to create a new directory **customXML**:
```bash
├── [Content_Types].xml
├── customXml
│   ├── item1.xml
│   ├── item2.xml
│   ├── item3.xml
│   ├── item4.xml
│   ├── itemProps1.xml
│   ├── itemProps2.xml
│   ├── itemProps3.xml
│   ├── itemProps4.xml
│   └── _rels
│       ├── item1.xml.rels
│       ├── item2.xml.rels
│       ├── item3.xml.rels
│       └── item4.xml.rels
├── customXML
│   ├── item5.xml
│   ├── itemProps5.xml
│   └── _rels
│       └── item5.xml.rels
├── docProps
│   ├── app.xml
│   ├── core.xml
│   └── custom.xml
├── _rels
└── word
    ├── document.xml
    ├── fontTable.xml
    ├── glossary
    │   ├── document.xml
    │   ├── fontTable.xml
    │   ├── _rels
    │   │   └── document.xml.rels
    │   ├── settings.xml
    │   ├── styles.xml
    │   └── webSettings.xml
    ├── _rels
    │   └── document.xml.rels
    ├── settings.xml
    ├── styles.xml
    ├── theme
    │   └── theme1.xml
    └── webSettings.xml

12 directories, 32 files
```

**Expected behavior**
The new files should be created within **customXml**

```bash
.
├── [Content_Types].xml
├── customXml
│   ├── item1.xml
│   ├── item2.xml
│   ├── item3.xml
│   ├── item4.xml
│   ├── item5.xml
│   ├── itemProps1.xml
│   ├── itemProps2.xml
│   ├── itemProps3.xml
│   ├── itemProps4.xml
│   ├── itemProps5.xml
│   └── _rels
│       ├── item1.xml.rels
│       ├── item2.xml.rels
│       ├── item3.xml.rels
│       ├── item4.xml.rels
│       └── item5.xml.rels
├── docProps
│   ├── app.xml
│   ├── core.xml
│   └── custom.xml
├── _rels
└── word
    ├── document.xml
    ├── fontTable.xml
    ├── glossary
    │   ├── document.xml
    │   ├── fontTable.xml
    │   ├── _rels
    │   │   └── document.xml.rels
    │   ├── settings.xml
    │   ├── styles.xml
    │   └── webSettings.xml
    ├── _rels
    │   └── document.xml.rels
    ├── settings.xml
    ├── styles.xml
    ├── theme
    │   └── theme1.xml
    └── webSettings.xml

10 directories, 32 files
```

**Desktop (please complete the following information):**
 - OS: Windows Server 2022 / Fedora 37
 - Office version -
 - .NET Target: .NET Framework 4.8
 - DocumentFormat.OpenXml Version: 2.19.0

**Additional context**
Maybe it could be narrowed down to this:
https://github.com/dotnet/Open-XML-SDK/blob/d46f92b2963f1c21415be08fb21532306e55db75/test/DocumentFormat.OpenXml.Packaging.Tests/data/PartConstraintData.json#L281

**Comment by twsouthwick** [comment]
@SimonSchwendele can you elaborate what you mean by this? I'm not sure what you mean by 'incomplete':

> rendering the document incomplete.

@tomjebo  can you look into the casing here? Probably another backend change

**Comment by SimonSchwendele** [comment]
> can you elaborate what you mean by this? I'm not sure what you mean by 'incomplete':
Word cant open it anymore.
When I open it in another program ( eg OnlyOffice ) I can at least open it but only part of my data is visible

**Comment by tomjebo** [comment]
@mikeebowen for backend review

**Comment by tomjebo** [comment]
so ISO 29500-1 15.2.5 Custom XML Data Storage Part shows an example of the path using caps for ML, i.e.  ../customXML/item1.xml. Besides that, it doesn't look like the standard or [MS-OI29500] specify anything for the path either way. But perhaps we should change this to be consistent with Word.

**Comment by SimonSchwendele** [comment]
>  But perhaps we should change this to be consistent with Word.

It might prevent some confusion.
Regarding `rendering incomplete` it appears that both docx files I used to test had broken bindings which is why they were displayed incomplete

**Comment by tomjebo** [comment]
@SimonSchwendele yeah, it really shouldn't matter if there are two paths to custom data, technically, as long as the application can get to them via relationships. But if SDK consumer code is trying to add *Word's* custom data, then they would need to use the same path. And having two paths is a bit wonky looking.

**Comment by tomjebo** [comment]
@mikeebowen if you're going to make a change in the schema processing for #1305, perhaps you can throw this one in at the same time?
