### ISSUE TITLE
Need to be able to add relationships, etc without using Package

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/Open-XML-SDK#1400]
How do I do this now that `Package` is `Obsolete`?
```cs
var newId = (uint)(spreadsheetDocument.Package.GetRelationships().Count() + 1);
var rId   = "relId" + newId;

...

spreadsheetDocument.Package.CreateRelationship(uri,
                                               TargetMode.Internal,
                                               "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet",
                                               rId);
```

It would be nice if the `Obsolete` message pointed us in the right direction. I'm rolling back to `2.19.0` for now.

_Originally posted by @michaelcsikos in https://github.com/dotnet/Open-XML-SDK/issues/1295#issuecomment-1506581653_

**Comment by twsouthwick** [comment]
@michaelcsikos Thanks for the feedback ! I've created this issue to track what to do here. Can I understand your scenario a bit more? If you're managing relationships on the package level, it may not be tracked correctly at the OpenXmlPackage level. I'd like to figure out what we can expose to enable your scenario without needing to manipulate the Package itself.

One possibility is to expose the Package property, but have it be the new abstraction we're using `IPackage`. It exposes mostly the same behavior - would that be sufficient? Adding relationships there would keep things in sync correctly between the two layers.

**Comment by michaelcsikos** [comment]
Hi @twsouthwick I've been using the following extension method for probably over ten years:
```cs
public static WorksheetPart InsertWorksheet(this SpreadsheetDocument spreadsheetDocument, string sheetName)
{
    var workbookPart = spreadsheetDocument.WorkbookPart;
    var workbook     = workbookPart.Workbook;
    var sheet        = GetSheet(spreadsheetDocument, sheetName);

    if (sheet != null)
        return (WorksheetPart)workbookPart.GetPartById(sheet.Id);

    uint newId = (uint)(spreadsheetDocument.Package.GetRelationships().Count() + 1);
    var  rId   = "relId" + newId;

    if (string.IsNullOrEmpty(sheetName))
        sheetName = "Sheet" + newId;

    int sheetnumber   = workbookPart.WorksheetParts.Count() + 1;
    var worksheetPart = workbookPart.AddNewPart<WorksheetPart>(rId);

    workbook.Sheets.Append(new Sheet() { Id = rId, SheetId = newId, Name = sheetName });

    var worksheet = new Worksheet();

    worksheetPart.Worksheet = worksheet;

    worksheet.AddNamespaceDeclaration("r", "http://schemas.openxmlformats.org/officeDocument/2006/relationships");

    worksheet.Append(new SheetDimension());
    worksheet.Append(new SheetViews(new SheetView() { WorkbookViewId   = 0 }));
    worksheet.Append(new SheetFormatProperties()    { DefaultRowHeight = 15 });
    worksheet.Append(new SheetData());
    worksheet.Append(new PageMargins() { Left = 0.7, Right = 0.7, Top = 0.75, Bottom = 0.75, Header = 0.3, Footer = 0.3 });

    var uri     = new Uri("worksheets/sheet" + sheetnumber + ".xml", UriKind.Relative);
    var package = spreadsheetDocument.Package;

    package.CreateRelationship(uri,
                               TargetMode.Internal,
                               "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet",
                               rId);
    package.Flush();

    return worksheetPart;
}
```

**Comment by davitescobedo** [comment]
Just to document it somewhere, with the new API one can create Relationships but there are only 2 overloads:
```
public string CreateRelationshipToPart(OpenXmlPart targetPart);
public string CreateRelationshipToPart(OpenXmlPart targetPart, string id);
```
So, to do what @michaelcsikos (and also I) need, you should add:
```public string CreateRelationshipToPart(OpenXmlPart targetPart, string relationshipType, string id);```
Correct me if I'm wrong, but TargetMode isn't needed here as it's TargetMode.Internal which is why we're using CreateRelationshipToPart, if TargetMode was External, we'd use 
```public ExternalRelationship AddExternalRelationship(string relationshipType, Uri externalUri, string id);```

There's also the need to add DeleteRelationship, which should look like:
```public void DeleteRelationship(string id);```

**Comment by RakhiNarayanan** [comment]
I am trying to use DocumentFormat::OpenXml::Packaging::IPackage,but it is throwing error while compilation.

error C4950: 'DocumentFormat::OpenXml::Packaging::IPackage': marked as obsolete
nvsdocument.cpp(399): note: Message: 'This is an experimental APIs and is subject to change'

Intially I was using System.IO.Packaging.Package` for openxmlsdk 2.19,whereas it is not supported in 3.0.2,how to resolve this error.

**Comment by twsouthwick** [comment]
See https://learn.microsoft.com/en-us/office/open-xml/general/diagnosticids#experimental-apis
