### ISSUE TITLE
Getting cell values is returning different format - OpenXML

### ISSUE THREAD

**Issue by kev-ops** [dotnet/Open-XML-SDK#1413]
**Describe the bug**
Getting cell value returns many decimal places. 

**Screenshots**
I have this "4.9" value in excel
![image](https://user-images.githubusercontent.com/15882382/233115011-f9670d58-d641-427b-aee0-b85eb9f60344.png)

When retrieving the cell value in OpenXML. 4.9 was stored as 4.90000000000000000000004. It should return value as it was inputted.
![image](https://user-images.githubusercontent.com/15882382/233115315-e6777836-f800-487f-b40e-389be4b6cd2f.png)

**To Reproduce**
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.

**Observed behavior**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Office version [e.g. 16.0.15427.20178]
 - .NET Target: (e.g. .NET Framework, .NET Core, UWP, Xamarin...)
 - DocumentFormat.OpenXml Version: (e.g. 2.11.0)

**Additional context**

**Comment by twsouthwick** [comment]
Can you share how you're doing this? Sounds like this is just an artifact of using a floating point number.

**Comment by twsouthwick** [comment]
This looks like something excel is adding and the SDK is surfacing that correctly. @tomjebo @mikeebowen please correct me, but I'm assuming this is because you mark it as number and general number must be using a float which are not able to [accurately represent numbers](https://stackoverflow.com/questions/21895756/why-are-floating-point-numbers-inaccurate). Could the `s="2"` value be the significant digits?

**Comment by kev-ops** [comment]
Yes, the number in my case "4.9" which is a general number resulted to [accurately represent numbers](https://stackoverflow.com/questions/21895756/why-are-floating-point-numbers-inaccurate). which is unwanted. 

_**Could the s="2" value be the significant digits?**_ 

Answer: I tried changing the value of AK3 cell on excel from 4.9 to string like "SAMPLE" and is in General format, the value of s remains "2". Refer to screenshot below:

![image](https://user-images.githubusercontent.com/15882382/233657520-2abe2684-4157-4774-938f-0764b41ebe2a.png)

So it is not a significant basis. t="s" refers to SharedString value I presume.

Please let me know if there will be some workaround on this issue. Thanks

**Comment by twsouthwick** [comment]
@tomjebo @mikeebowen thoughts as to what excel does here and if we can replicate it in the sdk?

**Comment by mikeebowen** [comment]
The `s` attribute is the index of the cell's style.

**Comment by mikeebowen** [comment]
I think the SDK is doing the correct thing here. [Excel stores numbers using double-precision](https://learn.microsoft.com/en-us/office/troubleshoot/excel/floating-point-arithmetic-inaccurate-result), so the value the SDK retrieves is correct. If the values stored by Excel in the underlying xml need to match what is displayed in the UI, users can set the [precision as displayed](https://learn.microsoft.com/en-us/office/troubleshoot/excel/floating-point-arithmetic-inaccurate-result#method-2-precision-as-displayed) option in Excel. With that option set Excel will store the exact decimal places showing in the UI. Note, this isn't retroactive, so if you set the "precision as displayed" option on a spreadsheet, new numbers will match the decimal places in the UI, but values entered before setting the option will remain double-precision.

**Comment by gartenkralle** [comment]
How does excel know when to show  4.9 or 4.90000000000000000000004?

**Comment by tomjebo** [comment]
@gartenkralle By the number formatting.

More: 

 Excel uses the `s` attribute in the cell element in the `sheet.xml` part: 

```xml
        <row r="7" spans="1:7" x14ac:dyDescent="0.25">
            <c r="A7" s="1">
                <v>3.05</v>
            </c>
        </row>
```

In this case the following `s` attribute is "1": 

```xml
 <c r="A7" s="1">
```

That corresponds to the second (zero based 1)  `cellXfs` entry in the `styles.xml` part: 

```xml
    <cellXfs count="2">
        <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
        <xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>
    </cellXfs>
```
which specifies the attribute value `numFmtId="164"` and  `applyNumberFormat="1"` (meaning to apply the number format of 164). That identifies the format in `numFmts`:

```xml
    <numFmts count="1">
        <numFmt numFmtId="164" formatCode="0.000"/>
    </numFmts>
```

Therefore displaying the value: 

![image](https://user-images.githubusercontent.com/4644198/236304530-51a57515-bdaf-448e-b3a9-a5ae3c884d50.png)

**Comment by kev-ops** [comment]
I also have relevant concern in date formatting

**Observed behavior**
Custom Date format and other date format returns inconsistent NumberFormatId 

Please refer to the attached file **1.xlsx**
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/80f145a0-4029-42e7-a796-2cf38e1215e7)

I have two custom date formats mm/dd/yyyy and mm-dd-yyyy. Checking it on XML it has numFmtId "164" and numFmtID "165" respectively.
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/f722e348-8b1a-4dc9-8e85-77de42b0693e)
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/519b5970-cde2-4fc1-b8ea-eb9f48409457)

![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/3aaa2778-ea55-407d-a646-872b82e1bd3a)

I have also this "2.xlsx" attached file which returns a different number format Ids for the same custom date format in "1.xlsx" file
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/3b2baf3c-d096-41a2-a71a-9a4380bc482e)
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/ac61ee56-08a8-465d-82f2-a2457262af3e)

Checking in on XML , it has numFmts "165" and "166" for **mm/dd/yyyy** & **mm-dd-yyyy respectively**
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/f76094f6-9250-481c-adc2-96b8d683b60e)

I have also this "3.xlsx" attached file which returns a different range of number format ids as well.
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/10e4775a-b773-4766-83e6-1b088f40bef2)
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/d9a7a4b7-351a-4a60-8bc2-5ecf8a03fb1a)

Checking it on XML , it has numFmtId = 171 & numFmtId = 172 for mm/dd/yyyy & mm-dd-yyyy respectively
![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/888ac9e3-4a28-4b1b-820d-62008b80e14f)

This also happens to other date formats as well not limited to custom date formats. We still don't know what is the basis of what numFmtId is assigned to particular date format.

How can we identify if a cell value in excel has date format (mm-dd-yyyy) or (mm/dd/yyyy) etc. ??

What we are trying to accomplish here is to check whether a cell value has (mm-dd-yyyy) or (mm/dd/yyyy) . Since NumFmtId assignment is not consistent.

Please see all files for your reference. Thank you! Hope to hear from you soon

[1.xlsx](https://github.com/dotnet/Open-XML-SDK/files/13686381/1.xlsx)
[2.xlsx](https://github.com/dotnet/Open-XML-SDK/files/13686382/2.xlsx)
[3.xlsx](https://github.com/dotnet/Open-XML-SDK/files/13686383/3.xlsx)

**Comment by kev-ops** [comment]
In addition, Is it possible to convert a date in c# using these formatCodes?

![image](https://github.com/dotnet/Open-XML-SDK/assets/15882382/29d8ca51-193e-418c-ac3c-5f587ffea9b1)

**Comment by mikeebowen** [comment]
Hi @kev-ops,  

> "We still don't know what is the basis of what numFmtId is assigned to particular date format. / How can we identify if a cell value in excel has date format (mm-dd-yyyy) or (mm/dd/yyyy) etc. ?"
- There is no way to find this with the Open XML SDK without examining the individual `numFmt` elements. You will have to examine the `numFmt` elements until you find the one you are searching for and then look at its `numFmtId` to find the ID value.
- More here on numFmt [2.1.712 Part 1 Section 18.8.30, numFmt (Number Format)](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oi29500/17d11129-219b-4e2c-88db-45844d21e528)
- And here [2.1.713 Part 1 Section 18.8.31, numFmts (Number Formats)](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oi29500/c6046ec6-f96d-4609-98e4-0dd549292955)
 
>  "Is it possible to convert a date in c# using these formatCodes? We are struggling converting the date values retrieved from excel in c# using the format codes in the screenshot."
- Yes, you can use the [DateTime Struct](https://learn.microsoft.com/en-us/dotnet/api/system.datetime?view=net-8.0)
- More on date formatting here [Standard date and time format strings](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings)

I hope that helps.

**Comment by greuelpirat** [comment]
I encountered the same problem but without style formatting. I just created a new sheet entered `147.61` to the first cell. I changed no style.

This was saved:
`<c r="B3"><v>147.61000000000001</v></c>`

And this is also what I get from `CellValue.Text`.

What is the recommended way to original the value?

**Comment by AlfredHellstern** [comment]
Can you please confirm that you used Excel when entering 147.61 initially? And what's your code when using CellValue.Text using the SDK?

**Comment by greuelpirat** [comment]
> Can you please confirm that you used Excel when entering 147.61 initially?

yes, this is easy to reproduce:

![Image](https://github.com/user-attachments/assets/1c814f3c-fb6a-4cbc-bf75-6daf670d37e9)

here the created sheet: [Mappe1.xlsx](https://github.com/user-attachments/files/17486193/Mappe1.xlsx)

> And what's your code when using CellValue.Text using the SDK?

Here the reduced code:
```csharp
string cellValue = cell.CellValue?.Text; // is '147.61000000000001'
if (cellValue == null)
    return null;
if (cell.DataType is { Value: var value }) // is null!
{ ... }
if (cell.StyleIndex != null) // is null!
{ ... }
return cellValue
```

cell.OuterXML is `<x:c r="A1" xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><x:v>147.61000000000001</x:v></x:c>` and that matches exactly the _Mappe1.xlsx_.

**Comment by mikeebowen** [comment]
@greuelpirat, this is the expected behavior, it is a result of how Excel stores numbers not the SDK. See this post above: https://github.com/dotnet/Open-XML-SDK/issues/1413#issuecomment-1520954222

**Comment by greuelpirat** [comment]
> [@greuelpirat](https://github.com/greuelpirat), this is the expected behavior, it is a result of how Excel stores numbers not the SDK. See this post above: [#1413 (comment)](https://github.com/dotnet/Open-XML-SDK/issues/1413#issuecomment-1520954222)

The option _Precision as displayed_ does not work here. The value is still saved with the appendix. For me it looks like the option only applies to _calculated_ cells. but not for inputs by the user since the option is the section _When calculating this workbook_

Anyway, I personally do not agree that this is expected behaviour (I definitely did not expect this). Anyone that comes across this issue will have to implement their own solution for this.

**Comment by hakito** [comment]
I agree with @greuelpirat. If it is expected behavior and you set the option precision as displayed. Then it's a bug!

**Comment by mikeebowen** [comment]
Hi @hakito and @greuelpirat, the extra decimals you see are a result of how Excel stores and calculates floating-point numbers, they can be confusing, but they are by design. More details on that how Excel handles floating-point numbers here: [Floating-point arithmetic may give inaccurate results in Excel](https://learn.microsoft.com/en-us/office/troubleshoot/excel/floating-point-arithmetic-inaccurate-result). 

There is no bug with the OpenXML SDK here. The SDK is correctly reading the values that Excel has stored. If you believe this is a bug in Excel, you can submit feedback on the [Excel Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/c23f3b77-f01b-ec11-b6e7-0022481f8472) or submit it to the Microsoft Feedback Hub, instructions on how to submit [here](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).
