### ISSUE TITLE
第一次用这个框架问下支不支持PPT动画就被QQ群踢了

### ISSUE THREAD

**Issue by dikastudio** [dotnet/Open-XML-SDK#1419]
**Is your feature request related to a problem? Please describe.**
Please link to an issue where the problem was reported if one exists.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
第一次用这个框架问下支不支持PPT动画就被QQ群踢了

Translation:
The first time I used this framework to ask if I didn't support PPT animation, I was kicked by the QQ group

**Comment by twsouthwick** [comment]
@dikastudio We need more information here. Please give some details as to what you're trying to do and what the issue is.

**Comment by twsouthwick** [comment]
Please reopen if more detail is available
