### ISSUE TITLE
Help with modern comments in PowerPoint

### ISSUE THREAD

**Issue by tomjebo** [dotnet/Open-XML-SDK#1433]
Hi @tomjebo @mikeebowen 
First point :
![image](https://user-images.githubusercontent.com/38904948/236021001-f1c1a584-971f-427c-aece-00e9bf1b789f.png)
could you please help me to update the above function that should work for "Modern" comments?

_Originally posted by @garg716 in https://github.com/dotnet/Open-XML-SDK/issues/1133#issuecomment-1533163265_

**Comment by garg716** [comment]
Hi @tomjebo @mikeebowen,
Tried to modify existing functions little bit :
`private static void **CopyComments365**(PresentationDocument oldDocument, PresentationDocument newDocument, SlidePart oldSlide, SlidePart newSlide)
        {
            if (oldSlide.commentParts.Any() == false)
                return;

            newSlide.AddNewPart<PowerPointCommentPart>();
            newSlide.commentParts.First().PutXDocument(oldSlide.commentParts.First().GetXDocument());
            XDocument newSlideComments = newSlide.commentParts.First().GetXDocument();
            XDocument oldAuthors = oldDocument.PresentationPart.authorsPart.GetXDocument();
            foreach (XElement comment in newSlideComments.Root.Elements(P188.cm))
            {
                XElement newAuthor = FindCommentsAuthor365(newDocument, comment, oldAuthors);
                // Update last index value for new comment
                comment.Attribute(NoNamespace.authorId).SetValue(newAuthor.Attribute(NoNamespace.id).Value);
                uint lastIndex = Convert.ToUInt32(newAuthor.Attribute(NoNamespace.lastIdx).Value);
                newAuthor.Attribute(NoNamespace.lastIdx).SetValue(Convert.ToString(lastIndex + 1));
            }
        }`

`private static XElement **FindCommentsAuthor365**(PresentationDocument newDocument, XElement comment, XDocument oldAuthors)
        {
            XElement oldAuthor =
                oldAuthors.Root.Elements(P188.cmAuthor).Where(f => f.Attribute(NoNamespace.id).Value == comment.Attribute(NoNamespace.authorId).Value).FirstOrDefault();
            XElement newAuthor = null;
            if (newDocument.PresentationPart.authorsPart == null)
            {
                newDocument.PresentationPart.AddNewPart<PowerPointAuthorsPart>();
                newDocument.PresentationPart.authorsPart.PutXDocument(
                    new XDocument(
                        new XElement(
                            P188.cmAuthorLst,
                            new XAttribute(XNamespace.Xmlns + "a", A.a),
                            new XAttribute(XNamespace.Xmlns + "r", R.r),
                            new XAttribute(XNamespace.Xmlns + "p188", P188.p188))));
            }
            XDocument authors = newDocument.PresentationPart.authorsPart.GetXDocument();
            newAuthor =
                authors.Root.Elements(P188.cmAuthor).Where(f => f.Attribute(NoNamespace.initials).Value == oldAuthor.Attribute(NoNamespace.initials).Value).FirstOrDefault();
            if (newAuthor == null)
            {
                uint newID = 0;
                IEnumerable<uint> ids = authors.Root.Descendants(P188.cmAuthor).Select(f => (uint)f.Attribute(NoNamespace.id));
                if (ids.Any())
                    newID = ids.Max() + 1;

                newAuthor = new XElement(
                    P188.cmAuthor,
                    new XAttribute(NoNamespace.id, oldAuthor.Attribute(NoNamespace.id).Value),
                    new XAttribute(NoNamespace.name, oldAuthor.Attribute(NoNamespace.name).Value),
                    new XAttribute(NoNamespace.initials, oldAuthor.Attribute(NoNamespace.initials).Value),
                    new XAttribute(NoNamespace.lastIdx, "1"),
                    new XAttribute(NoNamespace.clrIdx, oldAuthor.Attribute(NoNamespace.id).Value));
                authors.Root.Add(newAuthor);
            }

            return newAuthor;
        }`

but getting the following pop-up when trying to open the document
![image](https://github.com/dotnet/Open-XML-SDK/assets/38904948/30cce561-7e09-4ff3-a3d2-013c305bbc41)

could you please check where I am going wrong?

**Comment by christopherpcosta** [comment]
Do we also have any guidance on how to create modern comments in word? Using the current guide the comments do not appear in word online (they do appear in older versions and google docs) :(

**Comment by garg716** [comment]
Hi @tomjebo @mikeebowen,
Could you please help me on this https://github.com/dotnet/Open-XML-SDK/issues/1433#issuecomment-1555881553

Thanks,
Rahul

**Comment by mikeebowen** [comment]
Hi @garg716,

Have you looked at the [PowerPoint modern comments sample in the samples folder](https://github.com/dotnet/Open-XML-SDK/blob/main/samples/PowerPointModernCommentSample/Program.cs)?

**Comment by christopherpcosta** [comment]
@tomjebo @mikeebowen any pointers for me in the word context?

**Comment by garg716** [comment]
Hi @mikeebowen,

Can we achieve the modern comment using the following code?
Currently there is one issue => If a document is created in 365 and try to open it in 2016 then we got one error 
![image](https://github.com/dotnet/Open-XML-SDK/assets/38904948/45b08b21-06c5-4622-8be1-69c58d532644)

private static void **CopyComments365**(PresentationDocument oldDocument, PresentationDocument newDocument, SlidePart oldSlide, SlidePart newSlide)
        {
            if (oldSlide.commentParts.Any() == false)
                return;

            newSlide.AddNewPart<PowerPointCommentPart>();
            newSlide.commentParts.First().PutXDocument(oldSlide.commentParts.First().GetXDocument());
            XDocument newSlideComments = newSlide.commentParts.First().GetXDocument();
            XDocument oldAuthors = oldDocument.PresentationPart.authorsPart.GetXDocument();
            foreach (XElement comment in newSlideComments.Root.Elements(P188.cm))
            {
                XElement newAuthor = FindCommentsAuthor365(newDocument, comment, oldAuthors);
                // Update last index value for new comment
                comment.Attribute(NoNamespace.authorId).SetValue(newAuthor.Attribute(NoNamespace.id).Value);
                //uint lastIndex = Convert.ToUInt32(newAuthor.Attribute(NoNamespace.lastIdx).Value);
                //comment.Attribute(NoNamespace.idx).SetValue(lastIndex.ToString());
                //newAuthor.Attribute(NoNamespace.lastIdx).SetValue(Convert.ToString(lastIndex + 1));
            }

private static XElement **FindCommentsAuthor365**(PresentationDocument newDocument, XElement comment, XDocument oldAuthors)
        {
            XElement oldAuthor =
                oldAuthors.Root.Elements(P188.cmAuthor).Where(f => f.Attribute(NoNamespace.id).Value == comment.Attribute(NoNamespace.authorId).Value).FirstOrDefault();
            XElement newAuthor = null;
            if (newDocument.PresentationPart.authorsPart == null)
            {
                newDocument.PresentationPart.AddNewPart<PowerPointAuthorsPart>();
                newDocument.PresentationPart.authorsPart.PutXDocument(
                    new XDocument(
                        new XElement(
                            P188.cmAuthorLst,
                            new XAttribute(XNamespace.Xmlns + "a", A.a),
                            new XAttribute(XNamespace.Xmlns + "r", R.r),
                            new XAttribute(XNamespace.Xmlns + "p188", P188.p188))));
            }
            XDocument authors = newDocument.PresentationPart.authorsPart.GetXDocument();
            newAuthor =
                authors.Root.Elements(P188.cmAuthor).Where(f => f.Attribute(NoNamespace.initials).Value == oldAuthor.Attribute(NoNamespace.initials).Value).FirstOrDefault();
            if (newAuthor == null)
            {
                string userId = oldAuthor.Attribute(NoNamespace.userId).Value;
                newAuthor = new XElement(
                    P188.cmAuthor,
                    new XAttribute(NoNamespace.id, oldAuthor.Attribute(NoNamespace.id).Value),
                    new XAttribute(NoNamespace.name, oldAuthor.Attribute(NoNamespace.name).Value),
                    new XAttribute(NoNamespace.initials, oldAuthor.Attribute(NoNamespace.initials).Value),
                    new XAttribute(NoNamespace.userId, oldAuthor.Attribute(NoNamespace.userId).Value),
                    new XAttribute(NoNamespace.providerId, oldAuthor.Attribute(NoNamespace.providerId).Value));
                authors.Root.Add(newAuthor);
            }

            return newAuthor;
        }

**Comment by mikeebowen** [comment]
Hi @garg716 ,

The code you posted uses `XDocument`, `XAttribute`, etc. instead of using the classes and methods provided by the SDK, so I can't fix your code directly, but the sample code below will copy the comments from the first slide of a source PPTX to the first slide of a destination PPTX. I hope this helps.

```csharp
using (PresentationDocument srcPresentationDocument = PresentationDocument.Open(srcPptx, false))
using (PresentationDocument destPresentationDocument = PresentationDocument.Open(destPptx, true))
{
    if (destPresentationDocument is not null && destPresentationDocument.PresentationPart is not null && srcPresentationDocument is not null && srcPresentationDocument.PresentationPart is not null)
    {
        // If missing add the PowerPointAuthorsPart
        if (destPresentationDocument.PresentationPart.authorsPart is null)
        {
            destPresentationDocument.PresentationPart.AddNewPart<PowerPointAuthorsPart>();
        }

        // Add an AuthorList (p188:authorLst) element if missing
        if (destPresentationDocument.PresentationPart.authorsPart is not null && destPresentationDocument.PresentationPart.authorsPart.AuthorList is null && srcPresentationDocument.PresentationPart.authorsPart?.AuthorList is not null)
        {
            destPresentationDocument.PresentationPart.authorsPart.AuthorList = new AuthorList();
        }

        // Loop over the AuthorList (p188:authorLst) or the source PPTX and add a clone of each Author (p188:author) element
        if (destPresentationDocument.PresentationPart.authorsPart?.AuthorList is not null && srcPresentationDocument.PresentationPart.authorsPart?.AuthorList is not null)
        {
            foreach (Author author in srcPresentationDocument.PresentationPart.authorsPart.AuthorList)
            {
                destPresentationDocument.PresentationPart.authorsPart.AuthorList.AddChild(author.CloneNode(true));
            }
        }
        
        // Get the list of comment parts from the source document and the first slide part from the destination document
        List<PowerPointCommentPart>? powerPointCommentParts = srcPresentationDocument?.PresentationPart?.SlideParts.First().commentParts.ToList();
        SlidePart? destSlidePart = destPresentationDocument.PresentationPart.SlideParts.First();

        // If the destination slide does not have a presentation extension list add one and a presentaion extension with the Uri for a commentRel
        PresentationExtensionList presentationExtensionList = destSlidePart?.Slide?.GetFirstChild<PresentationExtensionList>() ??
            destSlidePart.Slide.AppendChild(
                    new PresentationExtensionList(
                        new PresentationExtension()
                        { Uri = "{6950BFC3-D8DA-4A85-94F7-54DA5524770B}" }));

        // Loop over the power point comment parts and add them to the destination slide part
        if (powerPointCommentParts is not null)
        {
            foreach (PowerPointCommentPart powerPointCommentPart in powerPointCommentParts)
            {
                destSlidePart.AddPart(powerPointCommentPart);
            }
        }
        // save the document
        if (destPresentationDocument.CanSave)
        {
            destPresentationDocument.Save();
        }
    }
}
```

**Comment by mikeebowen** [comment]
Hi @garg716, you haven't responded, so I will assume that the example code resolved your issue and close this issue. If you're still having issues, please respond and we can reopen this issue.
