### ISSUE TITLE
HightScale is misspelled in PropertySet.HightScale

### ISSUE THREAD

**Issue by lindexi** [dotnet/Open-XML-SDK#1441]
**Describe the bug**
The PropertySet.HightScale means `Specifies the amount that the height has been scaled by.`. 

The HightScale is misspelled. And I think it should be `HeightScale`.

Document: https://learn.microsoft.com/zh-cn/dotnet/api/documentformat.openxml.drawing.diagrams.propertyset.hightscale

**Screenshots**
None.

**To Reproduce**
None.

**Observed behavior**
None.

**Expected behavior**
None.

**Desktop (please complete the following information):**
None.

**Additional context**

**Comment by twsouthwick** [comment]
Thanks @lindexi this is still open for v3.0, so we should get this in.

@mikeebowen @tomjebo either of you interested in fixing that spelling?

**Comment by tomjebo** [comment]
sure, I'll fix it.

**Comment by twsouthwick** [comment]
@tomjebo  is this fixed?

**Comment by tomjebo** [comment]
> @tomjebo is this fixed?

Yup!
