### ISSUE TITLE
Update OpenXML MS documentation

### ISSUE THREAD

**Issue by farzonl** [dotnet/Open-XML-SDK#1442]
**Describe the bug**
After this commit a number of APIs were removed:
https://github.com/dotnet/Open-XML-SDK/commit/4260711d6234f078b24c26d26eb17205532901d5
For example
`GetPartsCountOfType` was removed but the documentation doesn't indicated deprectated or removed in the applies to section.
https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.packaging.openxmlpartcontainer.getpartscountoftype?view=openxml-2.8.1

infact the documentation hasn't been updated since 2.8.1 and these apis lived on through 2.20.0
https://github.com/dotnet/Open-XML-SDK/compare/v2.20.0...v3.0.0-beta1.patch

This is particularly unpleasant because the example code in the documentation is also incorrect: https://learn.microsoft.com/en-us/office/open-xml/how-to-insert-a-comment-into-a-word-processing-document

It does appear the documentation is hosted on github. Can you please update the documentation? While I muddled through, porting my app to the latest sdk, It would be good for future users of the sdk to have a single source of truth.

**Comment by twsouthwick** [comment]
This is underway! We had kind of left those docs unattended for a number of years... working to bring them back up to shape for the v3.0 release :) I'm going to close this issue in favor of this tracking issue: https://github.com/OfficeDev/open-xml-docs/issues/159. Please add any comments there for additional things that you may notice that need to be updated.

**Comment by twsouthwick** [comment]
FYI the api updates have been completed and the process is now known for updating for future releases
