### ISSUE TITLE
Migrate AzDo build, release pipeline to Github Actions

### ISSUE THREAD

**Issue by tomjebo** [dotnet/Open-XML-SDK#1453]
We currently have disabled PR triggered AzDo pipeline builds for security reasons. 
To resolve this, we should create a Github Action based pipeline. 

This issue should track the effort and discuss requirements, features needed, etc...

Current ability:

- [x] Remove current AzDo build from PRs/etc
- [x] Build/test all permutations of ProjectLoadStyle/os/configuration
- [x] See test failures/output
- [x] Build package
- [x] Sign package
- [x] Deploy package to CI feed on main
- [x] Deploy package to NuGet on GitHub releases (we can probably use an event here so when we create a release, it will automatically push the package to NuGet)
- [ ] Verify package names are what we expect

Additional we can add:

- [x] Benchmarks
- [x] Code coverage

**Comment by twsouthwick** [comment]
I've add a few of the requirements - are there others we want to make sure we do?

**Comment by twsouthwick** [comment]
@tomjebo any reason this is still open? I think you can close it out

**Comment by AlfredHellstern** [comment]
migration complete
