### ISSUE TITLE
DocumentFormat.OpenXml.Framework 3.0.0-beta0002

### ISSUE THREAD

**Issue by sergey-tihon** [dotnet/Open-XML-SDK#1475]
**Describe the bug**

> Error CS0246 : The type or namespace name 'PartTypeInfo' could not be found (are you missing a using directive or an assembly reference?)

Please release `DocumentFormat.OpenXml.Framework 3.0.0-beta0002` on Nuget

**To Reproduce**

`PartTypeInfo` was moved to the Framework library here https://github.com/dotnet/Open-XML-SDK/commit/a05cb788c2d75d81886e1a1d54e3fddc9d686068 but Framework beta2 is not released

Without the Framework library, ` DocumentFormat.OpenXml 3.0.0-beta0002` is not really usable.

**Comment by sergey-tihon** [comment]
Would be nice to unlist [3.0.0-ci0083](https://www.nuget.org/packages/DocumentFormat.OpenXml/3.0.0-ci0083) as well, because NuGet thinks that it is newer then [3.0.0-beta0002](https://www.nuget.org/packages/DocumentFormat.OpenXml/3.0.0-beta0002)

![image](https://github.com/dotnet/Open-XML-SDK/assets/1197905/66c0d67a-6993-4510-b90d-51301189b260)

**Comment by twsouthwick** [comment]
Both done :) Sorry for the confusion - we're switching parts of the build process (hopefully soon all on GH actions) and there has been a bit of a challenge with that.
