### ISSUE TITLE
Bug with Open XML SDK

### ISSUE THREAD

**Issue by kushalKPMS** [dotnet/Open-XML-SDK#1513]
**Describe the bug**
OpenXml.Packaging.WordProcessingDoucment.Open throws "Specified part does not exist in the package." not found even when all parts are present in the docx.
This seems to only happen when the docx has diagrams part in it and has a relationship specified in data.xml.rels. Specified relationship is as follows: "<Relationship Id="rId1" Type="http://schemas.microsoft.com/office/2007/relationships/diagramDrawing" Target="diagrams/drawing1.xml" />".
Removing the relationship seems to be able to open the document document but the relationship is a valid relation.

**Screenshots**

**To Reproduce**
Try to open any document having diagrams component in it and see the issue happening.

Use any document as file which contains drawing component in it.
Try to do OpenXml.Packaging.WordProcessingDoucment.Open
Observe that method throws Specified part not found in package exception even though all parts are present in the docx.

**Observed behavior**
Open method should not be throwing any exception.

**Expected behavior**
Document should open without any exceptions being thrown.

**Desktop (please complete the following information):**
 - OS: MacOs Ventura 13.2.1
 - Office version 
 - .NET Target: .NET 6.0
 - DocumentFormat.OpenXml Version: 2.20.0

**Additional context**
NA

**Comment by tomjebo** [comment]
>>Use any document as file which contains drawing component in it.

@kushalKPMS  can you be more specific about how you added a diagram? I tested with a new Word document and a smart art diagram and don't see the issue on 2.20.0 or our beta 3.0.

**Comment by tomjebo** [comment]
@kushalKPMS I'm closing this. If you can provide a repro code sample, then feel free to reopen.
