### ISSUE TITLE
Breaking change with Open XML SDK 3.0 in MarkupCompatibilityProcessMode.ProcessAllParts

### ISSUE THREAD

**Issue by sergey-tihon** [dotnet/Open-XML-SDK#1519]
**Describe the bug**
DocumentFormat.OpenXml `3.0.0-beta0002` removes custom attributes from elements on save, when `WordprocessingDocument` opened with `MarkupCompatibilityProcessSettings(MarkupCompatibilityProcessMode.ProcessAllParts, FileFormatVersions.Office2007)` 

Is it a bug or somewhere documented breaking change?

**Screenshots**
I've created a [repro code with a sample document](https://github.com/sergey-tihon/oxml-custom-attrs/blob/master/oxml3.tests/UnitTest.cs).

This sample 
1. Open a sample Word file using all 3 `MarkupCompatibilityProcessMode`s
2. Load `MainDocumentPart` as `XDocument`
3. Add custom `Unid` attribute (from fictional `pt14` namespace) to all elements
4. Add namespace to the list of `Ignorable` namespace
5. Save the document into a new file
6. Validate that the saved file contains added attributes. 

As you can see on the screenshot everything works as expected using `2.20.0` but does not work using `3.0.0-beta0002` with `MarkupCompatibilityProcessMode.ProcessAllParts`

<img width="850" alt="image" src="https://github.com/dotnet/Open-XML-SDK/assets/1197905/998dfd1d-84bf-4d1a-93a2-e933c50ed5fc">

**To Reproduce**

1. Clone repo https://github.com/sergey-tihon/oxml-custom-attrs/tree/master
2. Run unit test

**Observed behavior**
Document saved by `v2.20` with `MarkupCompatibilityProcessMode.ProcessAllParts `
<img width="1396" alt="image" src="https://github.com/dotnet/Open-XML-SDK/assets/1197905/7a97334e-a542-469f-aa5a-212df97191aa">

Document saved by `v3.0.0-beta0002` with `MarkupCompatibilityProcessMode.ProcessAllParts `
<img width="1420" alt="image" src="https://github.com/dotnet/Open-XML-SDK/assets/1197905/3500546f-173e-4b33-a367-78f23aa0fe66">

**Expected behavior**
The document should be saved as-is without removing attributes from Ignorable namespace.

**Desktop (please complete the following information):**
 - OS: macOS
 - .NET Target: .NET 7
 - DocumentFormat.OpenXml Version: 3.0.0-beta0002

**Additional context**
Found [during migrating](https://github.com/sergey-tihon/Clippit/pull/63) my fork of PowerTools to SDK v3

**Comment by twsouthwick** [comment]
Thanks for the bug report - I'll mark it for v3 release

**Comment by sergey-tihon** [comment]
Yes it is, just updated sample code/tests to [beta3](https://github.com/sergey-tihon/oxml-custom-attrs/commit/579a51d478ae0f68b0765c9492bb87266f9ceb13)

**Comment by twsouthwick** [comment]
@sergey-tihon, @tomjebo and I took a look at this and I think I have a grasp of what's going on. However, I'm not sure it's a bug, but rather we fixed previously bad behavior. Let me explain:

When you set `MarkupCompatibilityProcessMode.ProcessAllParts`, you're essentially telling the SDK to process all parts (kind of obvious, I know). When you update a part in this mode, upon final saving, we attempt to process the content. At this point, the attributes in the "Ignorable" namespaces are removed.

The bug was that there was an assumption before that the only changes to a document would be with the root element itself, not directly by the stream. This manifested in the code by a check to first see if any of the documents had their root loaded; if not, save was quickly exited. However, if a single part had been loaded, the whole load process kicked in.

As an example, make the following change to your code to simulate some code, somewhere loading a part somehow:

```diff
using (var doc = WordprocessingDocument.Open(ms, true, os))
{
+   // Force the root to be loaded on some other part
+   doc.ExtendedFilePropertiesPart!.Properties = new();

    var mainPart = doc.MainDocumentPart!;
    var xDocument = mainPart.GetXDocument();
    AssignUnidToAllElements(xDocument.Root!);
    IgnorePt14Namespace(xDocument.Root!);
    mainPart.PutXDocument();
}
``` 

Now, the same thing is seen on both v2.20.0 and v3.0.0. This to me feels like inconsistent behavior that is now fixed.

With all that said, how common is this pattern? Is it something you may be relying on? If so, there are ways to add compat switches to opt into certain behavior, but I'd only like to consider that if it is a common case.

**Comment by sergey-tihon** [comment]
> This manifested in the code by a check to first see if any of the documents had their root loaded; if not, save was quickly exited. 

Can you share the link to the source code with this check?

> doc.ExtendedFilePropertiesPart!.Properties = new();

With this change, Open XML SDK discards stream changes in all cases. Do you say that direct stream manipulation is an unsupported way of document modification using SDK?

> With all that said, how common is this pattern? Is it something you may be relying on?
 
Not common, I found it only in one place (inside OpenXmlPowerTools codebase) and still do no know why it was used.
https://github.com/sergey-tihon/Clippit/pull/63/files#diff-5cf3c4125c255f3512a8463ae45700630e8430986fb1dae26f30a6e0c73c5b97L57

>  If so, there are ways to add compat switches to opt into certain behavior, but I'd only like to consider that if it is a common case.

I think that it is worth mentioning as a breaking change. The decision about `compat switches` is up to you, probably is not needed for my use case.

**Comment by twsouthwick** [comment]
> > This manifested in the code by a check to first see if any of the documents had their root loaded; if not, save was quickly exited.

> Can you share the link to the source code with this check?

https://github.com/dotnet/Open-XML-SDK/blob/a873d3fbff9bffe179fea62486da950adf5be65d/src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs#L552-L565

>> doc.ExtendedFilePropertiesPart!.Properties = new();

> With this change, Open XML SDK discards stream changes in all cases. Do you say that direct stream manipulation is an unsupported way of document modification using SDK?

It's not that its discarded, it's just processed (per the options you specified). Either use a different processing option, or we can add a feature to suppress markup processing on a per-part basis that can be opted-into (probably not in time for v3.0 which we're aiming for the release around .NET 8)

**Comment by twsouthwick** [comment]
btw here's the docs about it that call out that setting the processing mode will affect what is saved: https://learn.microsoft.com/en-us/office/open-xml/introduction-to-markup-compatibility

**Comment by sergey-tihon** [comment]
> Finally, there is ProcessAllParts, which specifies what the name implies. When you choose this value, the entire document is preprocessed.

Does not it mean that in `ProcessAllParts` mode it should load and preprocess all parts (even those not loaded)?

**Comment by twsouthwick** [comment]
adding to docs: https://github.com/OfficeDev/open-xml-docs/pull/178
