### ISSUE TITLE
Open XML SDK v3: struct IdPartPair

### ISSUE THREAD

**Issue by sergey-tihon** [dotnet/Open-XML-SDK#1520]
**Describe the bug**
It would be nice to mention all v3-breaking changes in the release notes clearly.

**Screenshots**
Bug with the fix.
![image](https://github.com/dotnet/Open-XML-SDK/assets/1197905/d00a99ed-b473-45c0-9781-635d8d883864)

**To Reproduce**
`IdPartPait` has been converted from class to struct in v3 (most likely for performance reasons).

This change silently broke code that worked fine before and checked the value with `null`.
After the upgrade, the code compile without errors, but some branches became unreachable and app/library no longer works as expected.

**Observed behavior**
No release notes yet ;)

**Expected behavior**
Mention such cases inside the Breaking Changes section in released notes.

**Additional context**
I believe that it will be helpful for apps and library authors who decide to migrate to v3.
Found [during migrating](https://github.com/sergey-tihon/Clippit/pull/63) my fork of PowerTools to SDK v3

**Comment by sergey-tihon** [comment]
Just found that it was mentioned in the release notes for the beta1.
But I personally did not realise from this line how it would affect my code.

![image](https://github.com/dotnet/Open-XML-SDK/assets/1197905/15730867-5d23-4d41-8d84-1ca40e5b5b53)

**Comment by tomjebo** [comment]
Hey @sergey-tihon, 

Perhaps you're fine with this now but I thought I'd mention that I see that the compiler does at least inform you that this will always be true:

![image](https://github.com/dotnet/Open-XML-SDK/assets/4644198/46e3b5e0-abb7-44d2-b7b3-c70829967127)

**Comment by sergey-tihon** [comment]
Yes compiler informs with a warning, that it is truly hard to catch If you do not know that something will break.

I think that would be nice to mention in the release notes (breaking changes section) what warnings should be treated as errors during the migration to v3.

**Comment by twsouthwick** [comment]
Here's the docs for it: https://github.com/OfficeDev/open-xml-docs/blob/live/docs/migration/migrate-v2-to-v3.md.

I thought I had put a before/after recommendation on how to change this - but apparently it didn't make it there. Happy to take contribution there :)

**Comment by AlfredHellstern** [comment]
we consider this issue addressed. Please see twsouthwick's comments. Closing.
