### ISSUE TITLE
Microsoft Publisher support?

### ISSUE THREAD

**Issue by nojaf** [dotnet/Open-XML-SDK#1529]
Hello,

I'm trying to get rid of some old Office Interopt code and I'm looking for something to manipulate publisher documents. Is this something Open-XML-SDK supports as well?

**Comment by mikeebowen** [comment]
Hi @nojaf, What type of file are you trying to manipulate? When you say, "get rid of some old Office Interopt[sic] code", what kind of code do you mean?

**Comment by nojaf** [comment]
Hey @mikeebowen, I inherited a WinForms application yesterday that uses the Office COM interopt DLLs which I want to replace. The application does appear to manipulate an existing `*.pub` file.
My question is if the Open-XML-SDK can do this as well.

**Comment by mikeebowen** [comment]
Hi @nojaf, The OpenXML SDK provides strongly-typed classes to manipulate documents that adhere to the Office Open XML File Formats specification. The `*.pub` files do not adhere to these specifications, so it's not a supported file type.

**Comment by nojaf** [comment]
Thanks for pointing that @mikeebowen!
