### ISSUE TITLE
Any kind of documents has property DocumentType with value of the simple type(Workbook, Presentation, Document)

### ISSUE THREAD

**Issue by koviroli** [dotnet/Open-XML-SDK#1615]
**Describe the bug**

Opening any kind of document, let it be:
-  .docx, .docm, .dotm, .dotx
- .potm, .potx, .ppsm, .ppsx, .pptm, .ppss
- .xltx, .xlsm, .xlsx, .xltm,

the DocumentType property will always be `SpreadsheetDocumentType.Workbook` in case of Excel files, `PresentationDocumentType.Presentation` in case of PowerPoint files and `WordprocessingDocumentType.Document` in case of Word files.

**This is the behaviour with DocumentFormat.OpenXml 3.0.0.0 nuget package, but not with the previous version 2.20.0.**

**To Reproduce**

```
// DocumentFormat.OpenXML - 2.20.0 doc.DocumentType = MacroEnabledWorkbook
// DocumentFormat.OpenXML - 3.0.0 doc.DocumentType = Workbook
[Fact]
public void XlsmDocumentType_ShouldBe_MacroEnabledWorkbook()
{     
    // Path to a Macro-Enabled excel document       
    var fileBytes = File.ReadAllBytes(@"PathTo\Book1.xlsm");
    using (var m = new MemoryStream(fileBytes))
    using (var pkg = System.IO.Packaging.Package.Open(m))
    using (var doc = SpreadsheetDocument.Open(pkg))
    {           
        var expectedDocumentType = SpreadsheetDocumentType.MacroEnabledWorkbook;
        Assert.Equal(expectedDocumentType, doc.DocumentType);                
    }
}
```

**Observed behavior**
If I open any kind of Word-, Excel- or PowerPoint document, it will have a DocumentType property with value of WorkBook, in case of Excel, Presentation in case of PowerPoint and Document in case of Word document.

**Expected behavior**
If I open a Word-, Excel- or PowerPoint document, I expected to have DocumentType property with an enum value related to the document type, for example in case of Macro-Enabled Exel document, a `SpreadsheetDocumentType.MacroEnabledWorkbook`.

*Example*
Opening a Macro-Enabled excel file(*.xlsm):
Expected value of `DocumentType ` property: `MacroEnabledWorkbook`.
Actual value of `DocumentType ` property: `Workbook`

Opening a Macro-Enabled power point file(*.pptm):
Expected value of DocumentType property:  `MacroEnabledPresentation`
Actual value of `DocumentType ` property: `Presentation`

Opening a Macro-Enabled word file(*.docm):
Expected value of DocumentType property: `MacroEnabledDocument`
Actual value of `DocumentType ` property: `Document`

**Desktop (please complete the following information):**
 - OS: Windows
 - Office version: -
 - .NET Target: net6.0, net8.0
 - DocumentFormat.OpenXml Version: 3.0.0.0

**Comment by twsouthwick** [comment]
Thanks @koviroli  - I'll take a look.

**Comment by twsouthwick** [comment]
Fix was fairly straightforward. Should be released next week with v3.1

**Comment by koviroli** [comment]
Hi,
Do you have an estimation when will the v3.1 be released?

**Comment by twsouthwick** [comment]
sorry - out for the holidays then came down with covid again. I'm hoping to release a v3.0.1 with this fix as well as another one I'm pushing in now. Should be available in a couple of days

**Comment by koviroli** [comment]
@twsouthwick No worries, thank you for the update!
