### ISSUE TITLE
Bug with Open XML SDK -> Managed Debugging Assistant 'FatalExecutionEngineError' 

### ISSUE THREAD

**Issue by Matesax** [dotnet/Open-XML-SDK#1631]
Hi,
I do not know if there is hidden P-invoke in the Spreadsheet -> so that interface change manage to collapse OpenXml DLL, or if that is invoke inside OpenXml, that is crashing. So I am reporting this bug both in the OpenXml forum and SpreadsheetLight forum. The bug is very simple to reproduce -> problem is SpreadsheetLight Pivot reading with OpenXml version 3.0.0:

`Managed Debugging Assistant 'FatalExecutionEngineError' `
`Název chybujícího modulu: clr.dll, verze: 4.8.9181.0, časové razítko: 0x64b8594f
Kód výjimky: 0xc0000005
Posun chyby: 0x0001cca0
ID chybujícího procesu: 0x9b28
Čas spuštění chybující aplikace: 0x01da34a81bac4265
Cesta k chybujícímu modulu: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll`

With OpenXml version 2.20.0 there is no issue.

This crash is happening on the SLDocument creation from the stream:

`using (Stream inputStream = fsHelper.GetStream())
{
    Stopwatch sw;
    using (MemoryStream ms = new MemoryStream())
    {
        inputStream.CopyTo(ms);
        // load excel, and create a new workbook
        using (SLDocument sl = new SLDocument(ms))`

My project is basic .NET Framework 4.7 DLL with the Spreadsheet reading class. I have upgraded OpenXml based on Nuget recommendation -> and that was a mistake. :)

**Comment by twsouthwick** [comment]
Can you provide a repro project? As-is, I can't reproduce it. There is not "hidden pInvoke in the spreadsheet" and not sure what the SLDocument is doing

**Comment by Matesax** [comment]
Hello,
I do not understand, how simplier it coud be, but here you go:

[image: image.png]

With 2.20 no error:

[image: image.png]

**Comment by twsouthwick** [comment]
v3.0 is a major version and looks like you're updating it independently of a 3rd party library that was compiled against v2.x (SpreadsheetLight). That library will need to be recompiled in order to work with newer versions of the SDK
