### ISSUE TITLE
Issue with OpenXml WmlComparer when comparing documents with different numbering styles, Bug with Open XML SDK

### ISSUE THREAD

**Issue by yatintripathi** [dotnet/Open-XML-SDK#1634]
**Describe the bug**
I'm currently using the OpenXml library in C# to compare two Word documents utilizing the WmlComparer.Compare method. The comparison works well in most cases, but I'm encountering an issue specifically related to legal style numbering.

When comparing two documents, if one contains legal style numbering and the other doesn't, the resulting compared document loses the legal numbering entirely, without even maintaining a strikethrough format.

I've already implemented the comparison using WmlComparer.Compare and set the necessary comparison settings. However, I'm struggling to retain the legal style numbering or apply strikethrough formatting to the mismatched numbering when generating the compared document.

For more Reference :- [(https://stackoverflow.com/questions/77697178/issue-with-openxml-wmlcomparer-when-comparing-documents-with-different-numbering?noredirect=1#comment136981416_77697178)]

**Screenshots**
**These are how the documents look :-** 
![Screenshot (55)](https://github.com/dotnet/Open-XML-SDK/assets/108450640/66c5d736-3b39-4215-8064-1731a668946d)
![Screenshot (57)](https://github.com/dotnet/Open-XML-SDK/assets/108450640/27d0211c-4dba-46a9-a51c-e4933e3e950a)

**Microsoft Word's inherent working functionality :-**
![Screenshot (58)](https://github.com/dotnet/Open-XML-SDK/assets/108450640/e2dad431-87c5-4cb9-8d5f-a1070462fef5)

**OpenXML SDK WmlComparer working functionality :-**
![Screenshot (60)](https://github.com/dotnet/Open-XML-SDK/assets/108450640/f117a26b-e587-4fbf-acc2-8f3fe138b825)

Yo will see differences between Microsoft Word's inherent working functionality and OpenXML SDK WmlComparer working functionality.

****To Reproduce****
Create two docs in similar manner as in the screenshots of how the documents look and compare it via WmlComparer code you will be able to reproduce the Observed behavior and to reproduce the Expected behavior compare the two docs via compare functionality that word provides.
 
Steps to Reproduce the behavior:
1. Go to WORD.
2. Click on Review Tab and click on compare and compare two word documents , one with Legal Numbering System and one without it and compare.
3. You will see inherent working functionality of compare 
4. To generate Legal numbering in a word document
5. Click on Multilevel list on the taskbar of word
6. Click on  Define new multilevel list
7. Click on more
8. On the right hand side you will see a check box of Legal Numbering Style
9. Check it and press OK.

**Observed behavior**
As you can see from the screenshot above "OpenXML SDK WmlComparer working functionality" legal numbering is not retained.

**Expected behavior**
As you can see from the screenshot above "Microsoft Word's inherent working functionality" legal numbering is retained.

**Desktop (please complete the following information):**
 - OS: Windows
 - Office version : Version 2311 (Build 17029.20108)
 - .NET Target:  .NET Core Version 7.0.102
 - DocumentFormat.OpenXml Version: 2.20.0
 - OpenXMLPowerTools Version : 4.5.3.2

**Below is the code :-**

```
WmlComparerSettings settings = new WmlComparerSettings
            {
                AuthorForRevisions = author,
                DetailThreshold = 0
            };
            var originalDoc = new WmlDocument(originalPath.ToString());
            var revisedDoc = new WmlDocument(revisedPath.ToString());

            WmlDocument comparedDoc = WmlComparer.Compare(originalDoc, revisedDoc, settings);
```

@EricWhiteDev 
@ThomasBarnekow 
@twsouthwick 
@tomjebo @mikeebowen @hunyu @AlfredHellstern @lindexi

**Comment by lindexi** [comment]
@yatintripathi It seems that WmlComparer does not belong to the feature of this repo.

**Comment by yatintripathi** [comment]
@lindexi I tried to but their is no **Issues** tab open in that repository.

**Comment by yatintripathi** [comment]
@EricWhiteDev 
@ThomasBarnekow
@twsouthwick
@tomjebo @mikeebowen @hunyu @AlfredHellstern 
Can anyone help me with this ?

**Comment by ThomasBarnekow** [comment]
@yatintripathi, the only one able to help with this is @EricWhiteDev. He is the author of the `WmlComparer`, which is unfortunately very complex. Should he not be able to deal with this soon enough, you will unfortunately have to look into this yourself.

**Comment by yatintripathi** [comment]
@EricWhiteDev Could you please help me with this?

**Comment by JSv4** [comment]
@yatintripathi, would love to hear if you've found a solution to this one. Please report back!

**Comment by yatintripathi** [comment]
> @yatintripathi, would love to hear if you've found a solution to this one. Please report back!

@JSv4 no i didn't find any solutions yet.

**Comment by twsouthwick** [comment]
Since this is not a part of the SDK, I'm going to close it.

@ThomasBarnekow @EricWhiteDev you two are listed as owners on the OpenXmlDev org - is there a place this issue can be moved to be tracked near where WmlComparer is?

**Comment by ThomasBarnekow** [comment]
@twsouthwick, it seems @EricWhiteDev turned off issues for the Open-Xml-PowerTools repository. He is unfortunately the only one who can help with the WmlComparer, which is a very complex piece of software. The OP would have to contact Eric directly if he wants to ask for help. On the other hand, this is open source software, so the OP can at least try to fix this himself.

**Comment by yatintri** [comment]
@JSv4 , thrilled to hear about your project! I'll take a look at the code and familiarize myself with the project. Looking forward to being a part of this initiative!

**Comment by DandelionWenjing** [comment]
@yatintripathi Also have issues here, do you have any better solution for now? Thanks!

**Comment by yatintri** [comment]
> @yatintripathi Also have issues here, do you have any better solution for now? Thanks!

I solved this by using INTEROP instead of OPENXML.
