### ISSUE TITLE
Open XML create image from excel range

### ISSUE THREAD

**Issue by ppiredda** [dotnet/Open-XML-SDK#1654]
### Discussed in https://github.com/dotnet/Open-XML-SDK/discussions/1653

<div type='discussions-op-text'>

<sup>Originally posted by **ppiredda** January 23, 2024</sup>
Hi all, sorry but i have this problem: I create an Excel file and after that I need to collect row and columns (range) and create an image in order to send it to the clients. I found SpreadSheetGear and it works but it is very expensive. Is it possibile to do that directly with open xml? Thanks a lot for your collaboration. Help mi please. </div>

**Comment by AlfredHellstern** [comment]
Please ask this question on Stackoverflow. This is out of scope for the SDK.
