### ISSUE TITLE
[BUG] Cannot build fresh OpenXML-SDK

### ISSUE THREAD

**Issue by chacha21** [dotnet/Open-XML-SDK#1657]
I try to build OpenXML-SDK with the latest Visual Studio 2022 (community) (17.8.6)

- I git checkout the tag
- I open the *.sln
- I try to build the solution

My observations :

tag 2.7.2 

- works like a charm

tag 2.8.1

- Warning about Nuget vulnerabilities of some packages
- build fails with "The "GetAssemblyVersion" task has not been assigned a value for the required "NuGetVersion" parameter" (translated from french)

tag 2.9.1

- Warning about Nuget vulnerabilities of some packages
- build fails with "The "GetAssemblyVersion" task has not been assigned a value for the required "NuGetVersion" parameter" (translated from french)

tag 3.0.0

 - "Unable to resolve .NET SDK version as specified in global.json file" : => I had to install dotnet-sdk-7.0.201-win-x64
 - Warning The "OpenXmlGenerator" failed to generate the source. This will not contribute to the output and compilation errors may result. The exception was of type "FormatException" with the message "The format of the input string is incorrect".	DocumentFormat.OpenXml (net7.0) D:\Open-XML-SDK\3.0.1\src\DocumentFormat.OpenXml\CSC
- multiple errors of code compile refering to missing methods (because of missing assembly)

tag 3.0.1
 - same as tag 3.0.0
 
What is happening to that project ? There must be some broken automated action or wrong assumption about the host build machine.

**Comment by AlfredHellstern** [comment]
@twsouthwick, can you please take a look at the 3.0.0 issues?

**Comment by twsouthwick** [comment]
We regularly update to the latest SDK, so if you're jumping between versions, you'll potentially hit issues with different versions. Generally main expects latest SDK and VS fairly aggresively.

> "Unable to resolve .NET SDK version as specified in global.json file" : => I had to install dotnet-sdk-7.0.201-win-x64
Warning The "OpenXmlGenerator" failed to generate the source. This will not contribute to the output and compilation errors may result. The exception was of type "FormatException" with the message "The format of the input string is incorrect". DocumentFormat.OpenXml (net7.0) D:\Open-XML-SDK\3.0.1\src\DocumentFormat.OpenXml\CSC
multiple errors of code compile refering to missing methods (because of missing assembly)

This tells me you don't have the correct dotnet CLI. Can you run `dotnet --list-sdks"? v3.0.0 was built with the .net 7 sdk, while v3.0.1 (and main) uses .net 8.

**Comment by chacha21** [comment]
PM> dotnet --list-sdks
7.0.201 [C:\Program Files\dotnet\sdk]
8.0.101 [C:\Program Files\dotnet\sdk]

**Comment by twsouthwick** [comment]
I'm not sure why you're having issues. CI is building fine and I've had no issue with mine.

We do use a c# code generator (where your error is arising) - sometimes you have to restart VS to get it to work properly.

**Comment by twsouthwick** [comment]
do you have details on this:

> Warning The "OpenXmlGenerator" failed to generate the source. This will not contribute to the output and compilation errors may result. The exception was of type "FormatException" with the message "The format of the input string is incorrect". DocumentFormat.OpenXml (net7.0) D:\Open-XML-SDK\3.0.1\src\DocumentFormat.OpenXml\CSC

**Comment by chacha21** [comment]
@twsouthwick  Here is the build log with "diagnostics" verbosity level.
Could it be a parse error on my French system because the current local is using a "comma" as a decimal point separator ?
[openxmlsdk-3_0_1-build.log](https://github.com/dotnet/Open-XML-SDK/files/14433799/openxmlsdk-3_0_1-build.log)

**Comment by twsouthwick** [comment]
Hmm maybe. Can you set DocumentFormat.OpenXml.Generator as the startup project in VS and F5 it? That'll run the code generator under the debugger and should hopefully break for you when you hit the issue.

**Comment by chacha21** [comment]
> Hmm maybe. Can you set DocumentFormat.OpenXml.Generator as the startup project in VS and F5 it? That'll run the code generator under the debugger and should hopefully break for you when you hit the issue.

![dotnet-openxml-sdk](https://github.com/dotnet/Open-XML-SDK/assets/7251617/1fd41302-3023-41fe-be79-9c7b558cdbee)

**Comment by twsouthwick** [comment]
oh you need to install the ".NET Compiler Platform SDK" to be able to run it: https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/syntax-visualizer?tabs=csharp

**Comment by chacha21** [comment]
For information the problem still seems to be about decimal point.

`D:\Open-XML-SDK\3.0.1\src\DocumentFormat.OpenXml\DocumentFormat.OpenXml.Generator\DocumentFormat.OpenXml.Generator.OpenXmlGenerator\schemas_openxmlformats_org_spreadsheetml_2006_main.g.cs(27824,111,27824,111): error CS0594
`
Here is the line :
`builder.AddConstraint(new AttributeValueRangeConstraint(builder.CreateQName("x:degree"), true, -1,7E+308, true, 1,7E+308, true));`

As you can see, the "1,7E+308" has been generated with a french decimal point (comma). This is the reverse problem.

**Comment by chacha21** [comment]
And this is fixed by modifying StringSchematron.cs:280 from `return d.ToString();` to `return d.ToString(System.Globalization.CultureInfo.InvariantCulture);`

Then everything build OK.

Do you want me to PR or do you get it yourself ?

**Comment by twsouthwick** [comment]
I would love a PR for this! Thanks for investigating into this :)

**Comment by twsouthwick** [comment]
Thanks @chacha21 for the fix!
