### ISSUE TITLE
Bug with temp resources in v3 or higher

### ISSUE THREAD

**Issue by jrose323** [dotnet/Open-XML-SDK#1658]
After upgrading from 2.20.0 to 3.0.1, temp files are getting saved to the users temp folder when SpreadsheetDocument.Open is executed. This only occurs in v3.0 or higher. In addition to the temp files being created in the user temp folder which is new, Dispose() does not clear the temp files. So if the app is reading a large amount of spreadsheets, it eventually causes significant HDD capacity to be used.

Downgrading back to v2.20.0 resolves the issue

**Comment by craigomatic** [comment]
Noticed this also

**Comment by AlfredHellstern** [comment]
@twsouthwick can you take a look?

**Comment by oatkins** [comment]
Happy to see a fix for this, thank you! Do you have any estimate of when this fix might make it into a release?

**Comment by twsouthwick** [comment]
@AlfredHellstern  @mikeebowen we should probably do a 3.0.2 release with this before we do the schema updates for 3.1
