### ISSUE TITLE
Bug with Open XML SDK 3.0.1 : Spreadsheet Document Chart Scheme Color incorrect

### ISSUE THREAD

**Issue by tvbishan** [dotnet/Open-XML-SDK#1661]
**Describe the bug**
When I generate a .xlsx file which has a Chart with DocumentFormat.OpenXml 2.17.1, bars/lines of the chart have multiple colors. But with the DocumentFormat.OpenXml 3.0.1, only Blue color is there.

**Screenshots**
![image](https://github.com/dotnet/Open-XML-SDK/assets/12027448/0a23fbd2-898e-47fe-b3a1-ffd410c0085b)
![image](https://github.com/dotnet/Open-XML-SDK/assets/12027448/8a2edded-3e65-46b3-91fb-06bb5711dff5)
![image](https://github.com/dotnet/Open-XML-SDK/assets/12027448/897a1d12-f129-4b4a-be18-9b873551e020)

**Expected behavior**
Default behavior of having bars/lines of the chart with multiple colors .

**Desktop:**
 - OS: Window 10 / Alpine Linux 3.19
 - .NET Target: .NET Framework 4.7.2 / .NET Core 6
 - DocumentFormat.OpenXml Version: 3.0.1

**Comment by mikeebowen** [comment]
Hi @tvbishan, Can you supply a repro? I can't what's happening from just the xml.

**Comment by tvbishan** [comment]
Hi @mikeebowen,

I found that in openxml-2.17.1, SchemeColorValues is `enum` and in openxml-3.0.1, `struct`.

In my code, I have below line. (I have some other logics and I need this for verification purpose)
`SchemeColorValues schemeColorVal = (SchemeColorValues) Enum.Parse(typeof(SchemeColorValues), "Accent6");`

After upgrading to openxml-3.0.1, this line throws an exception because SchemeColorValues is `struct`.
