### ISSUE TITLE
This is might a bit off-topic, but let's discuss the transition of Open XML SDK to Rust

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/Open-XML-SDK#1663]
**This is might a bit off-topic, but let's discuss the transition of Open XML SDK to Rust**
Rust became a good enough language for development and backend services. And It is fast.

So, I put forward the idea of transitioning Open XML SDK to Rust.

There might be pros and cons, but I'd like to hear the community and contributors' responses on that.

**Comment by twsouthwick** [comment]
why? there's no way we would "transition" to rust - that implies getting rid of the .net version. Feel free to start a project to enable it in rust :)

**Comment by KaiserY** [comment]
Maybe a little outdated, but recently I made some experiments called [ooxmlsdk](https://github.com/KaiserY/ooxmlsdk). 

Similar to this project it takes `data` json for codegen. currently xml parsing/writing is ok, still no parts, validation, particle and of course no linq.

Feel free to check it if anyone is interested.
