### ISSUE TITLE
Unable to read cells with % symbol

### ISSUE THREAD

**Issue by NiranjanGodboleMaersk** [dotnet/Open-XML-SDK#1688]
I am working on Net core with Open XML. In my excel there is value 100%. I am trying to read as below

GetCellValue method

```
public static string GetCellValue(SpreadsheetDocument doc, Cell cell)
{
    if (cell.CellValue != null)
    {
        string value = cell.CellValue.InnerText;
        if (cell.DataType != null && cell.DataType.Value == CellValues.SharedString)
        {
            return doc.WorkbookPart.SharedStringTablePart.SharedStringTable.ChildElements.ElementAt(int.Parse(value)).InnerText;
        }
        else
        {
            return value;
        }
    }
    return string.Empty;
}
```

GetCell method

```
public static Cell GetCell(Worksheet worksheet, string columnName, uint rowIndex)
 {
     Row row = worksheet.GetFirstChild<SheetData>().Elements<Row>().FirstOrDefault(r => r.RowIndex == rowIndex);

     if (row != null)
     {
         return row.Elements<Cell>().FirstOrDefault(c => string.Compare(c.CellReference.Value, columnName + rowIndex, true) == 0);
     }
     return null;
 }
```

I am reading as below.

var data = OpenXmlReader.GetCellValue(spreadsheetDocument, OpenXmlReader.GetCell(workSheet, "E", 11));

The data is coming as 1 whereas actual value in my excel is 100%. I am not sure why this is not properly reading. Can someone please help me? Any help would be appreciated. Thanks

**Comment by mikeebowen** [comment]
Hi @NiranjanGodboleMaersk , what you see here is correct. In Excell, percentage values are saved as numbers from 0 - 1, then the percentage is a style applied by Excel, but the underlying data remains 0-1. The cell element that contains your value will be similar to:

```xml
<c r="A1" s="1">
  <v>1</v>
</c>
```

The `s` attribute on the cell (ISO/IEC 29500-1:2016 18.3.1.4 c (Cell)) represents the index of the cell's style. Style records are stored in the styles part. In the styles part, the `xf` element describes the formatting for a cell (ISO/IEC 29500-1:2016 18.8.45 xf (Format)).
