### ISSUE TITLE
Upgrading to 3+ can be troublesome for .NET6 projects

### ISSUE THREAD

**Issue by handerss-spotfire** [dotnet/Open-XML-SDK#1689]
The transition from 2.20 to 3.0 changed the dependency on [System.IO.Packaging](https://www.nuget.org/packages/System.IO.Packaging/) from `>=4.7.0` to `>=8.0.0`. For .NET6 projects its troublesome to use System.* packages with different major versions meaning upgrading to 3.0 is cumbersome (maybe impossible depending on how the dependency graph looks).

Was this change made intentionally to get access to newer APIs and if not can the dependency requirement at least be lowered to the lowest supported .NET version (e.g. 6.0.0)? If the change was intentional and the package now depends on new APIs introduced in 8.0.0 then feel free to close.

**Comment by twsouthwick** [comment]
The change is because there are performance and functional fixes in the packages that we want people to be opted into automatically.

Can you enumerate what issues you are having from upgrading to the latest System.* packages? I was not aware of issues in this space.

**Comment by handerss-spotfire** [comment]
> The change is because there are performance and functional fixes in the packages that we want people to be opted into automatically.

Alright, then the upgrade was intentional, thanks for the clarification. Feel free to close this issue.

> Can you enumerate what issues you are having from upgrading to the latest System.* packages? I was not aware of issues in this space.

The two main issues I recall are:

1. Upgrading a package cascades into forcing an upgrade of a different package which cannot be upgraded. E.g. for our case there were System.* packages which depended on System.Windows.Extensions which in turn depends on System.Drawing.Common (or it did in 7.0.0). Obviously these package "requirements" are imprecise since the only change from 6.0 to 7.0 for System.Drawing is that most methods throw exceptions.
2. Some System.* packages cannot be loaded using `AssemblyLoadContext.Default.LoadFromAssemblyPath` if they are part of the framework you are targeting. E.g. .NET 8 may have moved a package out of the framework distribution which means we cannot uphold a requirement of that package to be >=8.0.0 if we're targeting .NET 6.

For System.* packages there is a guarantee that security fixes are backported to the 6.0.x packages (see https://github.com/dotnet/runtime/issues/82225) so there is no point (from a security standpoint) of us upgrading to the 8.0.0 versions. However, for packages like this one I'm assuming no such guarantee exists.

AFAICT upgrading System.IO.Packaging should not cascade into any issues since it has not dependencies, so my fears are probably moot.

**Comment by twsouthwick** [comment]
I don't believe System.IO.Packaging v8.0.0 would cascade - https://www.nuget.org/packages/System.IO.Packaging/8.0.0#dependencies-body-tab shows that there are no dependencies for .net 6/7/8 so it should just update itself and not affect anything else.
