### ISSUE TITLE
[Performance] Reduce ElementFeatureCollection calls

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/Open-XML-SDK#1704]
**Is your feature request related to a problem? Please describe.**
This is only a performance report of something I noticed during profiling.

**Describe the solution you'd like**
A recent profiling session of a simple XML file with ~100_000 lines (by ~10 columns) showed that https://github.com/dotnet/Open-XML-SDK/blob/55f916df3dce862c71a16c59dd579b8d0d5fc152/src/DocumentFormat.OpenXml.Framework/Features/FeatureExtensions.cs#L19 takes ~25% of the time of the actual WriteTo calls.

<img width="752" alt="OptimizeFeatureExtensions" src="https://github.com/dotnet/Open-XML-SDK/assets/7989549/8497bacf-6a62-44fc-8c52-48cf8c6bda7a">
<img width="597" alt="OptimizeFeatureExtensions2" src="https://github.com/dotnet/Open-XML-SDK/assets/7989549/fab201d4-336b-4517-aa21-0fe583bde0cb">

I expect that the time is simply that much as it is called for each cell multiple times, each individual call is likely very short, but it simply adds up.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by twsouthwick** [comment]
Thanks for the report. Can you provide a repro we can add to our benchmarks?

**Comment by Tornhoof** [comment]
I'll see what I can do, I have yet to reproduce IT standalone.

**Comment by Tornhoof** [comment]
I managed to repro it and it's a bug in the code I was profiling.
For each cell, it tried to get the current Column via:
```csharp
   uint index = (uint) columnIndex + 1;
   column = columns.ChildElements.OfType<Column>().SingleOrDefault(a => a.Min! == index);
```
and apparently a new instance of ``OpenXmlElementList`` is returned each time and something in there triggered all these calls to ``GetRequired``.

The obvious solution was to move the column logic out of the inner loop.

I apologize for the noise.
