### ISSUE TITLE
Framework Support Update/Unclear

### ISSUE THREAD

**Issue by ludgerhachmeister** [dotnet/Open-XML-SDK#1728]
Hello,

the [NuGetGallery](https://www.nuget.org/packages/DocumentFormat.OpenXml/) specifies .NET 8.0 as supported target framework, while the README specifies .NET 6.0. What is the correct one?

**Comment by twsouthwick** [comment]
Both are supported. A .NET 6 project will use the .NET Standard build, while .NET 8 will use the specific build for it.
