### ISSUE TITLE
Bug - Method not found: 'Void DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Close()

### ISSUE THREAD

**Issue by adamjhilton** [dotnet/Open-XML-SDK#1752]
**Describe the bug**
I updated my NuGet packages and now I'm getting this error: 

`System.MissingMethodException: 'Method not found: 'Void DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Close()'.'`

Current versions:
- OpenXmlPowerTools: 4.5.3.2
- DocumentFormat.OpenXml: 3.0.2

The stack trace leaves my code here:
- at OpenXmlPowerTools.DocumentBuilder.BuildDocument(List`1 sources)

Looking at the decompiled assembly, there is a call to the [missing] OpenXmlPackage.Close() method:
```
 public static WmlDocument BuildDocument(List<Source> sources)
 {
  using OpenXmlMemoryStreamDocument openXmlMemoryStreamDocument = OpenXmlMemoryStreamDocument.CreateWordprocessingDocument();
  using (WordprocessingDocument wordprocessingDocument = openXmlMemoryStreamDocument.GetWordprocessingDocument())
  {
   BuildDocument(sources, wordprocessingDocument);
   ((OpenXmlPackage)wordprocessingDocument).Close();
  }

  return openXmlMemoryStreamDocument.GetModifiedWmlDocument();
 }
```

Here's the header from the decompiled assembly:
```
#region Assembly OpenXmlPowerTools, Version=4.5.3.0, Culture=neutral, PublicKeyToken=null
// C:\Users\ahilton\.nuget\packages\openxmlpowertools\4.5.3.2\lib\net45\OpenXmlPowerTools.dll
// Decompiled with ICSharpCode.Decompiler 8.1.1.7464
#endregion
```

I did notice that the version of the .DLL doesn't match the version of the NuGet package. I'm not sure if this is a problem or not. I don't think it is as the publish date matches. 
![image](https://github.com/user-attachments/assets/13997a51-009e-4ccf-a82c-aedf596aa379)

**Solution**
Reverting to DocumentFormat.OpenXml v2.20.0 resolves the issue. Although, I don't think I'd classify this as a "solution". But it works for now.

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro Version (10.0.22631 Build 22631)]
 - Office version [Microsoft® Outlook® for Microsoft 365 MSO (Version 2406 Build 16.0.17726.20078) 64-bit]
 - .NET Target: [.NET Framework 4.7.2]
 - DocumentFormat.OpenXml Version: [3.0.2]

**Comment by Numpsy** [comment]
Removing ```OpenXmlPackage.Close()``` was listed as a breaking change in the release notes for v3 - ref https://github.com/dotnet/Open-XML-SDK/issues/1298

**Comment by adamjhilton** [comment]
Ah... So, the author of the DocumentBuilder class in the OpenXmlPowerTools assembly hasn't removed the call to OpenXmlPackage.Close() yet? Got it. Hopefully, they'll update it eventually.

**Comment by moosa-bah** [comment]
Have you resolved that?  I still have that error and couldn't remove OpenXmlPackage.Close(), because the method DocumentBuilder.BuildDocument has that error.

**Comment by julienGrd** [comment]
same error here so also stuck to the 2.20 version, it seem the OpenXmlPowerTool pakage is dead as it didnt received any update in 5 years. 

I think the only solution is to remove our dependencies to OpenXmlPowerTool and find another package to realize the same operations.

**Comment by adamjhilton** [comment]
I'm just using the old version, as it still works fine. (For now at least...) I've added replacing OpenXmlPowerTools with an alternate package to my long term To Do List.

**Comment by meghanajakata** [comment]
What are the alternatives to OpenXmlPowerTools for merging two documents
