### ISSUE TITLE
Documentation Request: Explain how to "Splitting up (shredding) a file into multiple files, and combining multiple files into a single file."

### ISSUE THREAD

**Issue by catmanjan** [dotnet/Open-XML-SDK#1764]
**Describe the API or scenario**
One of the first features listed in this repo is:

"Splitting up (shredding) a file into multiple files, and combining multiple files into a single file."

But I can't find any information on the internet on how to split a file into multiple files using this SDK.

**Attempts**
Googled it

**Related scenarios**
All these questions but no code answers:

https://stackoverflow.com/questions/43659785/openxml-word-document-split
https://stackoverflow.com/questions/43659785/openxml-word-document-split
https://stackoverflow.com/questions/4920532/how-to-split-a-word-document-by-section-using-c-sharp-and-the-open-xml-sdk

**Comment by AlissaSabre** [comment]
@catmanjan 
I have no objection to add a set of tutorials and/or examples for the features listed on the repo's readme (if someone would do it...), but, if you are looking for a quick solution, you can check https://github.com/OpenXmlDev/Open-Xml-PowerTools. The class `DocumentBuilder` provides the requested feature for WordprocessingML (docx) document and `PresentationBuilder` for PresentationML (pptx) document. Their source files are in the folder `OpenXmlPowerTools`.

Hope this helps.

**Comment by mikeebowen** [comment]
Hi @catmanjan,

We're updating our existing documentation repo and moving the samples that exist in this repo to our documentation repo [OfficeDev/open-xml-docs](https://github.com/OfficeDev/open-xml-docs), so the best place to request new samples/documentation is on the OfficeDev/open-xml-docs [issues page](https://github.com/OfficeDev/open-xml-docs/issues)

**Comment by AlfredHellstern** [comment]
Closing. Please see Mike's comments.
