### ISSUE TITLE
Open XML SDK bug?

### ISSUE THREAD

**Issue by ghost** [dotnet/Open-XML-SDK#1779]
Hi

I use a library called spreadsheetlight.
This uses open xml sdk.

This is the problem I have:

https://github.com/ARLM-Keller/SpreadsheetLight/issues/3

Is this a open xml sdk bug?

**Comment by AlfredHellstern** [comment]
Not an SDK bug. SpreadsheetLight would need to update to using the latest SDK. This project hasn't seen any changes over the last 8 years. We'd recommend forking this or switching to a different, more up-to-date library.
