### ISSUE TITLE
Unable to Create Custom Icon Set for Conditional Formatting

### ISSUE THREAD

**Issue by gergelyurbancsik** [dotnet/Open-XML-SDK#1783]
**Describe the bug**
I am trying to set up conditional formatting in an Excel file using the DocumentFormat.OpenXml library. Specifically, I want to use a red X and a green checkmark from the ThreeSymbols icon set. However, this icon set also includes a yellow exclamation mark, which I do not want to use. The issue is that the library does not allow the creation of a custom icon set to exclude the yellow exclamation mark.

**To Reproduce**

1.	Create a new Excel file.
2.	Apply conditional formatting using the ThreeSymbols icon set.
3.	Attempt to customize the icon set to exclude the yellow exclamation mark.

**Expected behavior**
•	If the value is equal to 0, no icon should be displayed.
•	If the value is equal to 1, a green checkmark icon should be displayed.
•	If the value is greater than 1, a red X icon should be displayed.

Additional Information: I also tried using the IconFilter class, but it did not work as expected.
**Additional context**
`using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml;
using System;
using System.Collections.Generic;
using DocumentFormat.OpenXml.Office2010.Excel;
using ConditionalFormatting = DocumentFormat.OpenXml.Spreadsheet.ConditionalFormatting;
using ConditionalFormattingRule = DocumentFormat.OpenXml.Spreadsheet.ConditionalFormattingRule;
using IconSet = DocumentFormat.OpenXml.Spreadsheet.IconSet;

namespace ConsoleApp5
{
    public class ExcelHeaderProtection
    {
        public void ConditionalFormattingIconSet()
        {
            using (var spreadsheetDocument = SpreadsheetDocument.Create(@"C:\temp\EXCEL_EXCEL\ConditionalFormattingIconSet.xlsx", SpreadsheetDocumentType.Workbook))
            {
                var workbookPart = spreadsheetDocument.AddWorkbookPart();

                var worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
                var workbook = new Workbook();

                var worksheet = new Worksheet();
                worksheetPart.Worksheet = worksheet;

                AddDataConditionalFormattingIconSet(workbookPart, worksheetPart);

                var cColumn = worksheet.AppendChild(new ConditionalFormatting());
                cColumn.SequenceOfReferences = new ListValue<StringValue> { InnerText = "C:C" };

                // Rule for Red X
                var cfRuleRedX = cColumn.AppendChild(new ConditionalFormattingRule());
                cfRuleRedX.Type = ConditionalFormatValues.IconSet;
                cfRuleRedX.Priority = 1;

                var iconSetRedX = new IconSet()
                {
                    ShowValue = false,
                    Reverse = false,
                    IconSetValue = new EnumValue<IconSetValues>(IconSetValues.ThreeSymbols)
                };

                iconSetRedX.AppendChild(new ConditionalFormatValueObject
                {
                    Type = ConditionalFormatValueObjectValues.Number,
                    Val = "0",
                    GreaterThanOrEqual = BooleanValue.FromBoolean(true),
                });
                iconSetRedX.AppendChild(new ConditionalFormatValueObject
                {
                    Type = ConditionalFormatValueObjectValues.Number,
                    Val = "1",
                    GreaterThanOrEqual = BooleanValue.FromBoolean(false),
                });
                iconSetRedX.AppendChild(new ConditionalFormatValueObject
                {
                    Type = ConditionalFormatValueObjectValues.Number,
                    Val = "2",
                    GreaterThanOrEqual = BooleanValue.FromBoolean(false),
                });

                cfRuleRedX.Append(iconSetRedX);

                // Rule for Green Check
                var cfRuleGreenCheck = cColumn.AppendChild(new ConditionalFormattingRule());
                cfRuleGreenCheck.Type = ConditionalFormatValues.IconSet;
                cfRuleGreenCheck.Priority = 2;

                var iconSetGreenCheck = new IconSet()
                {
                    ShowValue = false,
                    Reverse = false,
                    IconSetValue = new EnumValue<IconSetValues>(IconSetValues.ThreeSymbols)
                };

                iconSetGreenCheck.AppendChild(new ConditionalFormatValueObject
                {
                    Type = ConditionalFormatValueObjectValues.Number,
                    Val = "0",
                    GreaterThanOrEqual = BooleanValue.FromBoolean(false),
                });
                iconSetGreenCheck.AppendChild(new ConditionalFormatValueObject
                {
                    Type = ConditionalFormatValueObjectValues.Number,
                    Val = "1",
                    GreaterThanOrEqual = BooleanValue.FromBoolean(false),
                });
                iconSetGreenCheck.AppendChild(new ConditionalFormatValueObject
                {
                    Type = ConditionalFormatValueObjectValues.Number,
                    Val = "2",
                    GreaterThanOrEqual = BooleanValue.FromBoolean(true),
                });

                cfRuleGreenCheck.Append(iconSetGreenCheck);

                worksheetPart.Worksheet.Save();
                var sheets = new Sheets();
                var sheet = new Sheet();
                sheet.Name = "Sheet1";
                sheet.SheetId = 1;
                sheet.Id = workbookPart.GetIdOfPart(worksheetPart);
                sheets.Append(sheet);
                workbook.Append(sheets);

                spreadsheetDocument.WorkbookPart.Workbook = workbook;
                spreadsheetDocument.WorkbookPart.Workbook.Save();
            }
        }

        internal void AddDataConditionalFormattingIconSet(WorkbookPart workbookPart, WorksheetPart worksheetPart)
        {
            SheetData sheetData = new SheetData();

            var sharedStringPart = workbookPart.AddNewPart<SharedStringTablePart>();
            sharedStringPart.SharedStringTable = new SharedStringTable();
            sharedStringPart.SharedStringTable.AppendChild(new SharedStringItem(new Text("Default Three Arrows")));
            sharedStringPart.SharedStringTable.AppendChild(new SharedStringItem(new Text("Custom ThreeTrafficLights2 Minimum:25% Maximum:75%")));
            sharedStringPart.SharedStringTable.AppendChild(new SharedStringItem(new Text("Default Five Rating")));

            var row1 = new Row() { RowIndex = 1 };
            var row2 = new Row() { RowIndex = 2 };
            var row3 = new Row() { RowIndex = 3 };

            sheetData.Append(row1);
            sheetData.Append(row2);
            sheetData.Append(row3);

            var cellA1 = new Cell() { CellReference = "A1", DataType = new EnumValue<CellValues>(CellValues.SharedString) };
            cellA1.CellValue = new CellValue("0");
            var cellA2 = new Cell() { CellReference = "A2", DataType = new EnumValue<CellValues>(CellValues.SharedString) };
            cellA2.CellValue = new CellValue("1");
            var cellA3 = new Cell() { CellReference = "A3", DataType = new EnumValue<CellValues>(CellValues.SharedString) };
            cellA3.CellValue = new CellValue("2");

            row1.Append(cellA1);
            row2.Append(cellA2);
            row3.Append(cellA3);

            row1.Append(new Cell() { CellReference = "B1", CellValue = new CellValue("1") });
            row1.Append(new Cell() { CellReference = "C1", CellValue = new CellValue("2") });
            row1.Append(new Cell() { CellReference = "D1", CellValue = new CellValue("3") });
            row1.Append(new Cell() { CellReference = "E1", CellValue = new CellValue("4") });
            row1.Append(new Cell() { CellReference = "F1", CellValue = new CellValue("5") });

            row2.Append(new Cell() { CellReference = "B2", CellValue = new CellValue("1") });
            row2.Append(new Cell() { CellReference = "C2", CellValue = new CellValue("2") });
            row2.Append(new Cell() { CellReference = "D2", CellValue = new CellValue("3") });
            row2.Append(new Cell() { CellReference = "E2", CellValue = new CellValue("4") });
            row2.Append(new Cell() { CellReference = "F2", CellValue = new CellValue("5") });

            row3.Append(new Cell() { CellReference = "B3", CellValue = new CellValue("1") });
            row3.Append(new Cell() { CellReference = "C3", CellValue = new CellValue("2") });
            row3.Append(new Cell() { CellReference = "D3", CellValue = new CellValue("3") });
            row3.Append(new Cell() { CellReference = "E3", CellValue = new CellValue("4") });
            row3.Append(new Cell() { CellReference = "F3", CellValue = new CellValue("5") });

            worksheetPart.Worksheet.Append(sheetData);
        }
    }
}
`

**Comment by mikeebowen** [comment]
duplicate, answered in #1784
