### ISSUE TITLE
A basic OpenXml created Workbook breaks in 'Spreadsheet Compare'

### ISSUE THREAD

**Issue by TrevorT** [dotnet/Open-XML-SDK#1789]
**Describe the bug**
I came across this in a more complicated scenario (creating a SpreadsheetDocument from an existing stream, modifying the doc and streaming it out to another different file), but I've distilled the issue to the below example.
In my test the Excel file is created and valid, but trying to use it in "Spreadsheet Compare" causes that app to crash with a "Attempt to read past end of stream" exception.
Opening the generated file in Excel, and saving it again (unchanged) fixes the issue - so the save from within Excel is modifying (fixing) the document. 

**To Reproduce**
Use the following test to create the workbook:
```
        [Fact]
        public void CreateAndSaveSpreadsheet()
        {
            // Arrange
            string outputFilename = Path.Combine(Path.GetDirectoryName(GetType().Assembly.Location)!, "OutputFolder", "Blank Document Created.xlsx");

            if (File.Exists(outputFilename))
                File.Delete(outputFilename);

            // Act
            using (SpreadsheetDocument spreadsheetDoc = SpreadsheetDocument.Create(outputFilename, SpreadsheetDocumentType.Workbook))
            {
                WorkbookPart workbookPart = spreadsheetDoc.AddWorkbookPart();
                workbookPart.Workbook = new Workbook();

                WorksheetPart worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
                worksheetPart.Worksheet = new Worksheet(new SheetData());

                Sheets sheets = spreadsheetDoc.WorkbookPart.Workbook.AppendChild(new Sheets());

                Sheet sheet = new Sheet()
                              {
                                  Id = spreadsheetDoc.WorkbookPart.GetIdOfPart(worksheetPart),
                                  SheetId = 1,
                                  Name = "Sheet1"
                              };
                sheets.Append(sheet);

                // Save the Workbook
                workbookPart.Workbook.Save();
                spreadsheetDoc.Save();
            }
        }
```

1. Run the test to create the (basically empty) Workbook.
2. Run Spreadsheet Compare. Choose the above created file for one of the comparison files
3. See error:
![image](https://github.com/user-attachments/assets/9fa52709-ea37-42a5-877b-f7c783a1554c)
4. To reproduce a 'fix': Open the created doc in Excel, save it unchanged, redo the Spreadsheet compare (no exception occurs)

**Observed behavior**
Unexpected exception.

**Expected behavior**
No exception from spreadsheet compare.
No significant internal file changes when an OpenXml created Workbook is opened in Excel and saved unchanged.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Office version: Office 365:  
![image](https://github.com/user-attachments/assets/a8655a23-6601-403e-9ece-4d58a4f9a89e)
 - .NET Target: .Net 6.0
 - DocumentFormat.OpenXml Version: 2.20.0

**Additional context**
Some investigation has led me to believe that the presence of the `xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main"`
entry for the default namespace, and the corresponding x: namespace prefixes to the xml tags is the issue. 
![image](https://github.com/user-attachments/assets/439be7e4-ad5b-4383-8b34-c04ef91b96e0)

If I manually edit the internals of the xlsx (sheet1.xml ) file and change the default namespace to have no alias in the 'sheet1.xml' file (as below) the issue is fixed (Spreadsheet Compare does not fail).
![image](https://github.com/user-attachments/assets/5d25b44f-5b3f-474f-8b68-0e19381c001b)

I have found to no way to get OpenXml to remove the x alias for the default namespace declared in the document XML.

**Comment by JarRami** [comment]
Seems this was reported earlier atleast at https://github.com/dotnet/Open-XML-SDK/issues/509 but a fix was never reached? I'm running into this through ClosedXML (for.ex. https://github.com/ClosedXML/ClosedXML/issues/1436) and would be nice to have it fixed.

**Comment by twsouthwick** [comment]
This is valid xml and conforms to the spec. The issue lies in Spreadsheet Compare for some reason not correctly handling xml namespaces.

I'm going to close this issue, but if you want to provide an opt-in way to control the namespaces, feel free to reopen and submit a PR.

**Comment by databird** [comment]
Very old post... but same problem in 2026 ! The "x:" namespace is still added and can cause problem on some other software that import XLSX.

Here's our hack :

When creating the speadsheet, just before disposing, we call 2 customs functions :

```
SpreadsheetDocument spreadsheetDoc = DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(this._spreadsheetDocumentStream, true)

// your code that generate the XLSX

// Fixing problem :
FixAllWorksheetDimensions(spreadsheetDoc); //only needed if software report wrong number of lines
RemovePrefixesEverywhere(spreadsheetDoc); //remove bad namespace

spreadsheetDoc.Dispose();
```

And here's the customs functions :

```
private void RemovePrefixesEverywhere(SpreadsheetDocument doc)
{
    foreach (var part in doc.GetAllParts())
    {
        try
        {
            string xml;
            using (var reader = new StreamReader(part.GetStream(FileMode.Open, FileAccess.Read)))
            {
                xml = reader.ReadToEnd();
            }
            if (xml.StartsWith("<?xml"))
            {
                // remove all "x:" prefixes and xmlns:x declaration
                xml = xml.Replace("<x:", "<").Replace("</x:", "</").Replace("xmlns:x=", "xmlns=");
                using (var writer = new StreamWriter(part.GetStream(FileMode.Create, FileAccess.Write)))
                {
                    writer.Write(xml);
                }
            }

        } catch { /* ignore parts that are not XML (e.g. images) */ }
    }
}
private void FixAllWorksheetDimensions(SpreadsheetDocument doc)
{
    foreach (var wsPart in doc.WorkbookPart.WorksheetParts)
    {
        var sheetData = wsPart.Worksheet.GetFirstChild<SheetData>();
        if (sheetData == null || !sheetData.Elements<Row>().Any())
            continue;

        uint minRow = sheetData.Elements<Row>().Min(r => r.RowIndex.Value);
        uint maxRow = sheetData.Elements<Row>().Max(r => r.RowIndex.Value);

        // max length = number of columns of the longest row
        int maxColIndex = sheetData.Elements<Row>()
                                   .Max(r => r.Elements<Cell>().Count());
        string maxCol = GetExcelColumnReference(maxColIndex);

        string dimensionRef = $"A{minRow}:{maxCol}{maxRow}";
        var dim = wsPart.Worksheet.GetFirstChild<SheetDimension>();
        if (dim == null)
        {
            dim = new SheetDimension();
            wsPart.Worksheet.InsertAt(dim, 0);
        }

        dim.Reference = new DocumentFormat.OpenXml.StringValue(dimensionRef);
        wsPart.Worksheet.Save();
    }
}
```

Enjoy it :-)
