### ISSUE TITLE
External hyperlinks (`Relationship`) with a space character within its address breaks Excel 2007.

### ISSUE THREAD

**Issue by VladiStep** [dotnet/Open-XML-SDK#1790]
**Describe the bug**
This issue is a kind of link to this issue - https://github.com/ClosedXML/ClosedXML/issues/2397
Feel free to close this issue as invalid if it's necessary (I don't have enough time to properly describe this right now).

**Screenshots**

**To Reproduce**
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.

**Observed behavior**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Office version [e.g. 16.0.15427.20178]
 - .NET Target: (e.g. .NET Framework, .NET Core, UWP, Xamarin...)
 - DocumentFormat.OpenXml Version: (e.g. 2.11.0)

**Additional context**

**Comment by igitur** [comment]
> I don't have enough time to properly describe this right now

Make bug reports great again!

**Comment by AlfredHellstern** [comment]
closing as not actionable. Please reopen with more details if needed.
