### ISSUE TITLE
FontName becomes OpenXmlUnknownElement

### ISSUE THREAD

**Issue by andrewtsybulia** [dotnet/Open-XML-SDK#1792]
Hi team
**Describe the bug**
After updating to version 3.1.0, I've encountered a bug. When I create a **DocumentFormat.OpenXml.Spreadsheet.RunProperties** with **FontName** as a child element, it changes the **FontName** to **OpenXmlUnknownElement**.

**Screenshots**
![image](https://github.com/user-attachments/assets/192c235f-4f24-4305-b82e-b791533a4b30)

**To Reproduce**
```csharp
using System.Linq;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Xunit;

namespace SOME_NAME_SPACE;

public class ExcelConvertingHelperTests
{
    [Fact]
    public void BuildFont_Should_Return_RunProperties_With_FontName()
    {
        // Arrange
        var runProps = new RunProperties(new FontName());
        var spreadsheetDocument = SpreadsheetDocument.Create($"SampleWithRunProperties.xlsx", SpreadsheetDocumentType.Workbook);
        var workbookPart = spreadsheetDocument.AddWorkbookPart();
        var worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
        worksheetPart.Worksheet = new Worksheet(new SheetData(new Row(new Cell(new InlineString(new Run(runProps))))));
        workbookPart.Workbook = new Workbook(new Sheets(new Sheet()));
        spreadsheetDocument.Save();

        // Act
        var result = worksheetPart.Worksheet.Descendants<RunProperties>().First().FirstChild;

        // Assert
        Assert.True(result is FontName);
        Assert.True(result is not OpenXmlUnknownElement);

        spreadsheetDocument.Dispose();
    }
}
```
1. Run the test
2. See error

**Expected behavior**
FontName becomes OpenXmlUnknownElement, I expect it to stay FontName.

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise 23H2
 - .NET Target: .Net 8.0
 - DocumentFormat.OpenXml Version: 3.1.0

**Comment by rettoua** [comment]
any thoughts on that ? @twsouthwick

**Comment by twsouthwick** [comment]
This is intentional - `FontName` is not a correct child for this. Unfortunately, the constructor as it is will happily take an unexpected child and add it to the collection.

```diff
using System.Linq;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Xunit;

namespace SOME_NAME_SPACE;

public class ExcelConvertingHelperTests
{
    [Fact]
    public void BuildFont_Should_Return_RunProperties_With_FontName()
    {
        // Arrange
-       var runProps = new RunProperties(new FontName());
+       var runProps = new RunProperties();
+       runProps.AddChild(new FontName(), throwOnError: true); // throws - xml is serialized as `x:name`
+       runProps.AddChild(new RunFont(), throwOnError: true);  // works - xml is serialized as `x:rFont`
        var spreadsheetDocument = SpreadsheetDocument.Create($"SampleWithRunProperties.xlsx", SpreadsheetDocumentType.Workbook);
        var workbookPart = spreadsheetDocument.AddWorkbookPart();
        var worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
        worksheetPart.Worksheet = new Worksheet(new SheetData(new Row(new Cell(new InlineString(new Run(runProps))))));
        workbookPart.Workbook = new Workbook(new Sheets(new Sheet()));
        spreadsheetDocument.Save();

        // Act
        var result = worksheetPart.Worksheet.Descendants<RunProperties>().First().FirstChild;

        // Assert
        Assert.True(result is FontName);
        Assert.True(result is not OpenXmlUnknownElement);

        spreadsheetDocument.Dispose();
    }
}
```

@tomjebo can you verify with the schema spec that this is correct behavior?

**Comment by tomjebo** [comment]
Yes, that is correct behavior. `FontName` is a wrapper for `x:name` which is the name of a font but used in the `<x:Fonts><x:Font>...` collection in the styles part, not in run properties for an inline string. `RunFont` is a wrapper for `x:rfont` which belongs in the `<x:r><x:rPr><x:t>...` block of a rich text in-line string. So what @twsouthwick said is right.

**Comment by twsouthwick** [comment]
I'm going to go ahead and close this then.

As of v3, elements that are not known children of an element are not reconstructed and default to an unknown element. This is part of an ongoing effort to minimize what an element might root for AOT scenarios. If this is a problem, please open a new issue to discuss that.
