### ISSUE TITLE
How to insert image into cell in xlsx file?

### ISSUE THREAD

**Issue by HansiZou** [dotnet/Open-XML-SDK#1816]
I hope use openxml insert image into one cell(embed) in xlsx file。
then use winrar unzip this xlsx。
dir:
![Image](https://github.com/user-attachments/assets/af15cf1d-5e53-4751-a940-8dacee103335)
![Image](https://github.com/user-attachments/assets/4828be9c-892a-4c04-bb07-49b1d78f451e)
![Image](https://github.com/user-attachments/assets/8846bccd-2b52-4f1f-9b13-6060d8914e9f)
I want to have relations 
cellimages.xml
![Image](https://github.com/user-attachments/assets/261a4712-aacb-4859-91d7-ada690dd9561)
cellimages.xml.rels
![Image](https://github.com/user-attachments/assets/ca1283e9-155a-4acf-8986-f3e489affd40)

**Comment by ThomasBarnekow** [comment]
@HansiZou, please ask that question on [stackoverflow](https://stackoverflow.com) rather than opening an issue in this repository.
