### ISSUE TITLE
Add SVG as ImagePartType for Office 2016 support

### ISSUE THREAD

**Issue by koyote** [dotnet/Open-XML-SDK#204]
Hi,

Office 2016 now (finally) supports svg as a vector image format (https://support.office.com/en-gb/article/Insert-SVG-images-in-Microsoft-Office-69f29d39-194a-4072-8c35-dbe5e7ea528c)
As far as I can see the OpenXml SDK does not currently have support for this yet (as ImagePartType for example).
Are there any plans of adding it in the future, or any roadblocks that might inhibit implementing it?

**Comment by stefan505** [comment]
Yes please, would like it as well!

**Comment by prashantsoni** [comment]
Yes, It would be great to include this.

**Comment by twsouthwick** [comment]
We're looking at what needs to be done to get the Office 2016 code merged in. We're hoping sooner than later :) I'm not certain if this support is already there, so I'll leave this open to track it

**Comment by stefan505** [comment]
Any progress on this?

**Comment by zhijieshi** [comment]
Any progress? Thanks.

**Comment by cbryan-risklens** [comment]
Is there any guess about when this will be added?

**Comment by raudabaugh** [comment]
I started trying to add support for this but got stuck when I realized that the generated code is missing type definitions for http://schemas.microsoft.com/office/drawing/2016/SVG/main. Are the xsd files and code generation steps for this publicly available somewhere?

**Comment by twsouthwick** [comment]
Unfortunately, they're not available. We're trying to get things updated and would like to make them public, but that hasn't happened yet.

**Comment by twsouthwick** [comment]
Sorry this got closed. Reopening and we're looking into this now.

**Comment by mattiamerzi** [comment]
> Sorry this got closed. Reopening and we're looking into this now.

Hi, sorry for bothering you, have you got any news about this?

Thanks a lot!

**Comment by mikeebowen** [comment]
- #1031 
Resolves this issue.
